### ISSUE TITLE
Ubuntu16.04开启TIM 开启微信后  无法通过通知栏唤醒TIM,Ubuntu 18.04一切正常，建议大家用18.04

### ISSUE THREAD

**Issue by leixd1994** [wszqkzqk/deepin-wine-ubuntu#1]
![screenshot from 2018-07-06 16-31-03](https://user-images.githubusercontent.com/23328517/42368744-737e64ea-813a-11e8-9da0-3fea4c73cbf8.png)

**Comment by wszqkzqk** [comment]
我这里可以

**Comment by wszqkzqk** [comment]
好像是腾讯的锅要用右键点。

**Comment by leixd1994** [comment]
![screenshot from 2018-07-08 10-06-49](https://user-images.githubusercontent.com/23328517/42416038-a53e80f2-8296-11e8-86b0-dd3a99cce148.png)
@wszqkzqk  升级到18.04后就好了  18.04是这样的
