### ISSUE TITLE
百度云官方客户端

### ISSUE THREAD

**Issue by updater1234** [wszqkzqk/deepin-wine-ubuntu#117]
百度云官方低调推出了Linux客户端。
![火狐截图_2019-06-23T06-30-02 800Z](https://user-images.githubusercontent.com/31512600/59972536-6a887580-95c3-11e9-872a-e82fb258ff73.png)

**Comment by updater1234** [comment]
不过目前只有rpm和deb两种格式.

**Comment by wszqkzqk** [comment]
好，但是还是保留wine版

**Comment by updater1234** [comment]
那请问一下作者，能否把deb重新打包一下放到AUR上面？

**Comment by wszqkzqk** [comment]
已经有了虽然不是我做的。
