### ISSUE TITLE
微信小程序开发工具不能运行

### ISSUE THREAD

**Issue by OneQuid** [wszqkzqk/deepin-wine-ubuntu#126]
靠自己解决不了，来请教一下。
`README`中提到的*阿里云*镜像中下载的[deepin.com.wechat.devtools](https://mirrors.aliyun.com/deepin/pool/non-free/d/deepin.com.wechat.devtools/)
最初有依赖问题，使用的dpkg
>$ sudo dpkg -i package_name.deb

然后运行了 apt 指令，没有依赖报错了
>$ sudo apt --fix-broken install

依赖的问题应该是复现不了了，只记得有七八个依赖缺少
- wine
- wine32
- ...

从菜单打不开，从terminal运行指令
>$ "/opt/deepinwine/apps/Deepin-WeChatDev/run.sh"

提示
>./nw: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

查了下`libXtst`库已经安装

再用GUI打开deb包，显示如下
![Screenshot at 2019-07-08 16-28-28](https://user-images.githubusercontent.com/49135017/60795026-85e7a900-a19d-11e9-8f66-dc9c8f60afad.png)

----
系统是：
Ubuntu Mate 18.04.1 AMD64

**Comment by SoulSu** [comment]
使用这个方法sudo apt-get install libxtst6:i386

**Comment by OneQuid** [comment]
@SoulSu 
安装`libxtst6:i386`之后确实可以显示登录界面了，谢谢
