### ISSUE TITLE
英文系统所有软件都没法现实中文

### ISSUE THREAD

**Issue by houxd** [wszqkzqk/deepin-wine-ubuntu#137]
在/opt/deepinwine/tools/run.sh 中添加了LC_ALL="zh_CN.UTF-8"可以解决问题, 希望维护者修改下, 例如

env LC_ALL="zh_CN.UTF-8" WINEPREFIX="$WINEPREFIX" $WINE_CMD "c:\\DecryptDoc.exe " &

**Comment by naodai** [comment]
可以解决中文乱码的问题。
昨天升级了系统，然后就都乱码了，微信，tim，

**Comment by 724399396** [comment]
我的也是进行了apt upgrade之后出现了显示不正常，修改 /opt/deepinwine/tools/run.sh 的WINE_CMD 加入LC_ALL=zh_CN.UTF-8 以后显示正常了，但是搜狗输入法依然没办法使用。

**Comment by wszqkzqk** [comment]
好吧，可以采纳

**Comment by wszqkzqk** [comment]
我还是觉得这个无法合并
因为某些容器涉及权限
都是用的官方原文件

**Comment by wszqkzqk** [comment]
我可以写在readme.md里面说明一下

**Comment by OneQuid** [comment]
用上面提到的方法， TIM群里的公告 还是会显示不正确。
刚刚改别的东西，发现好了。

简单试了下还原 `run.sh` ,去掉`WINE_CMD`中的`LC_ALL=zh_CN.UTF-8`也可以正常现实的，应该是因为这个。

操作是将`/etc/fonts/conf.avail/64-language-selector-prefer.conf`中的所有`<family>Noto Serif CJK SC</family>`移到`<family>Noto Sans Mono CJK JP</family>`之前，保存就可以了。

如
```
                 <prefer>
                        <family>Noto Serif CJK JP</family>
                        <family>Noto Serif CJK KR</family>
                        <family>Noto Serif CJK SC</family>
                        <family>Noto Serif CJK TC</family>
                </prefer>
```
改为
```
                <prefer>
                        <family>Noto Serif CJK SC</family>
                        <family>Noto Serif CJK JP</family>
                        <family>Noto Serif CJK KR</family>
                        <family>Noto Serif CJK TC</family>
                </prefer>
```
希望这个能有帮助

**Comment by thomas0713** [comment]
> 用上面提到的方法， TIM群里的公告 还是会显示不正确。
> 刚刚改别的东西，发现好了。
> 
> 简单试了下还原 `run.sh` ,去掉`WINE_CMD`中的`LC_ALL=zh_CN.UTF-8`也可以正常现实的，应该是因为这个。
> 
> 操作是将`/etc/fonts/conf.avail/64-language-selector-prefer.conf`中的所有`<family>Noto Serif CJK SC</family>`移到`<family>Noto Sans Mono CJK JP</family>`之前，保存就可以了。
> 
> 如
> 
> ```
>                  <prefer>
>                         <family>Noto Serif CJK JP</family>
>                         <family>Noto Serif CJK KR</family>
>                         <family>Noto Serif CJK SC</family>
>                         <family>Noto Serif CJK TC</family>
>                 </prefer>
> ```
> 
> 改为
> 
> ```
>                 <prefer>
>                         <family>Noto Serif CJK SC</family>
>                         <family>Noto Serif CJK JP</family>
>                         <family>Noto Serif CJK KR</family>
>                         <family>Noto Serif CJK TC</family>
>                 </prefer>
> ```
> 
> 希望这个能有帮助

还是不可以，微信的中文还是竖条的

**Comment by OneQuid** [comment]
@thomas0713 请问logout login 还是有这问题吗？我看了下微信也可以了，我是走了什么好运？

**Comment by thomas0713** [comment]
@OneQuid 我试了上面加环境变量的方法好了，你说的那种我试了，重启也不行，可能是系统什么东西装的和你不一样吧

**Comment by OneQuid** [comment]
@thomas0713 好，感觉会对这个产生影响的修改就这一个，可能遗漏了什么。或者因为我现在用的是Ubuntu Mate？不过想换个桌面了
