### ISSUE TITLE
QQ TIM都不能使用中文输入法

### ISSUE THREAD

**Issue by rayliu3798** [wszqkzqk/deepin-wine-ubuntu#141]
试了很多方法都不行，有解决了的吗？

**Comment by wszqkzqk** [comment]
以fcitx为例：编辑/etc/profile
在末尾加上：
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

**Comment by rayliu3798** [comment]
大佬，还是不行呢。
在/opt/deepinwine/apps和/opt/deepinwine/tools下面的run.sh也加了
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
还是不能切换输入法。

**Comment by wufe8** [comment]
+1 同样
/etc/profile ¬/.bashrc /opt/deepinwine/apps /opt/deepinwine/tools的都加了 
自带的ibus卸了 仍然不行
qq qq轻聊 tim均测试过
ubuntu 18.04; deepin-wine 2.18
