### ISSUE TITLE
Ubuntu18.04微信中文都是竖条

### ISSUE THREAD

**Issue by thomas0713** [wszqkzqk/deepin-wine-ubuntu#143]
Ubuntu18.04微信中文都是竖条，重启，重安装微信，重安装deepin环境，重装系统，都没有解决。

**Comment by fzxiao233** [comment]
Ubuntu18.04QQ TIM同一现象

**Comment by zhseasm** [comment]
系统语言非中文时，中文全显示成方块，需要在

/opt/deepinwine/tools/run.sh

中将 WINE_CMD 那一行修改为

WINE_CMD="LC_ALL=zh_CN.UTF-8 deepin-wine"

@thomas0713 @fzxiao233 试试

**Comment by shunzh** [comment]
https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/136#issuecomment-514585722
我follow的这个就好了。

**Comment by thomas0713** [comment]
已经解决了，谢谢 @zhseasm @shunzh

**Comment by crab-in-the-northeast** [comment]
f
