### ISSUE TITLE
Ubuntu 18.04 微信有两个窗口

### ISSUE THREAD

**Issue by shunzh** [wszqkzqk/deepin-wine-ubuntu#144]
除了微信窗口以外，还有一个叫ChatContactMenu的空窗口。

![Screenshot from 2019-07-26 22-29-16](https://user-images.githubusercontent.com/4490965/61988977-05c39f00-aff7-11e9-8148-be35649bafdf.png)

**Comment by OneQuid** [comment]
重启几次微信就好了，如果哪位有一劳永逸的解决方案就更完美。

昨天刚换了 Linux Mint Cinnamon，偶尔也会遇到这个问题。除了你提到的 有时会出现一个置顶的黑框，菜单中显示的是Deepin-Wine-... 之类的 下次遇到了截图上来。

两个还没有**同时出现**过。

**Comment by shunzh** [comment]
黑框是自定义表情提示框的问题，随便输个能提示自定义表情的文字（哈哈 666 之类的）就好了。
https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/72

**Comment by OneQuid** [comment]
学到了 谢谢 @shunzh

**Comment by shunzh** [comment]
@OneQuid 没遇到过你说的问题，开个issue问问？

**Comment by grayguest** [comment]
@onequid 厉害，好奇你怎么发现输入@可以解决这个问题的。我和你的情况一样，用的是mint 19.3 cinnamon

**Comment by onequid** [comment]
运气好
