### ISSUE TITLE
安装deepin-wine后，ubuntu16.04进不了桌面了，只适用于kde桌面？

### ISSUE THREAD

**Issue by scm20008** [wszqkzqk/deepin-wine-ubuntu#147]
![2019-07-31_090657](https://user-images.githubusercontent.com/639305/62176046-950fe000-b372-11e9-9478-af559cc3cc8f.png)

错误如上图，进不了桌面了。
环境：ubuntu-16.04-x64-desktop

**Comment by wszqkzqk** [comment]
不

**Comment by wszqkzqk** [comment]
不要点KDE安装脚本

**Comment by scm20008** [comment]
谢谢，我自己解决 了，upgrade一下就好了。和kde没有关系。
