### ISSUE TITLE
微信输入框字体黑条

### ISSUE THREAD

**Issue by drZhan** [wszqkzqk/deepin-wine-ubuntu#166]
我安装deepin wine过程中没有发生错误，然后使用的是dpkg -i 进行安装微信（deepin.com.wechat_2.6.8.52deepin0_i386）
报错：
dpkg: dependency problems prevent configuration of deepin.com.wechat:i386:
 deepin.com.wechat:i386 depends on deepin-wine-helper (>= 1.2deepin2); however:
  Version of deepin-wine-helper:i386 on system is 1.2deepin0.
这个是怎么回事呢，忙活了好久都没解决。已经尝试过重新安装，修复依赖（apt install -f 直接把微信删除了）。

**Comment by gemini4545** [comment]
我才装的微信也是这个问题，那么是如何解决这个问题的呢？

**Comment by gemini4545** [comment]
> 
> 
> 微信汉字显示无异常，但是在输入文字的对话框里面的汉字会变成黑条，而英文、数字和标点均正常。
> 输入的文字（显示为黑条）发出后，可在记录上方正常显示。

我才装的微信也是这个问题，那么是如何解决这个问题的呢？

**Comment by yopoing** [comment]
同求解决办法，偶尔会遇到这个问题

**Comment by xixinzhang** [comment]
同问题
