### ISSUE TITLE
qq 2018 那个安装包不能用了，估计腾讯封了，说安全隐患，提示安装最新版本

### ISSUE THREAD

**Issue by rw15250** [wszqkzqk/deepin-wine-ubuntu#204]

**Comment by zhuozl** [comment]
me too !!!

**Comment by 644517236** [comment]
+1

**Comment by liujianchina** [comment]
me too!!!!!!!   SOS...

**Comment by 644517236** [comment]
暂时用这个  https://www.ubuntukylin.com/applications/23-cn.html  吧 虽然这个操作快了就闪退,但是版本比较新

**Comment by CrazyPigHead** [comment]
可以先用TIM     https://mirrors.aliyun.com/deepin/pool/non-free/d/deepin.com.qq.office/

**Comment by 1221zcz** [comment]
俺也一样!

**Comment by YaoLaiGang** [comment]
Tim和QQ不行了，只能勉强用QQ刚出的Linux版，太垃圾了

**Comment by glory15022** [comment]
只能用Tim了

**Comment by mengmengtian** [comment]
+1

**Comment by driftluo** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=183719&extra=&highlight=qq&page=1

download 9.1.8 here, it works now but has some problem, I don't know if the repository has been updated to this version？
```
dpkg: dependency problems prevent configuration of deepin.com.qq.im:i386:
 deepin.com.qq.im:i386 depends on deepin-wine-helper (>= 1.2deepin2); however:
  Version of deepin-wine-helper:i386 on system is 1.2deepin0.
```

**Comment by b1oodgemini** [comment]
俺也一样，不过用了TIM发现意外的还不错

**Comment by anurnomeru** [comment]
转战tim = = 最主要的原因还是官方linux版qq什么都没，仿佛回到十几年前 = =

**Comment by llCnll** [comment]
一个闪退就在也登不上去了....

**Comment by Kewth** [comment]
+1

**Comment by luckxiang** [comment]
俺也一样，俺也一样，俺也一样

**Comment by shawnl111** [comment]
+1

**Comment by GitAndGithub** [comment]
#189 
> [ubuntu18.04安装新版deepin-wine环境](https://forum.ubuntu.org.cn/viewtopic.php?f=73&p=3217021&sid=6194a64cefc1f4c5ac43dcd8729ca3c8)

**Comment by zq1997** [comment]
旧版本已经不能用了，deepin也放出了新安装包。
[# 20](https://github.com/zq1997/deepin-wine/issues/20)###

**Comment by wszqkzqk** [comment]
现在可以用新版了

**Comment by TheThreeDog** [comment]
心态炸了。搞了个一模一样的Ubuntu虚拟机装上新的都能使了，我本机就是不行。

**Comment by YaoLaiGang** [comment]
> 心态炸了。搞了个一模一样的Ubuntu虚拟机装上新的都能使了，我本机就是不行。
> 
> ----------结贴-----------
> 已解决：
> https://blog.csdn.net/Three_dog/article/details/103017873

我的可以安装上，但是卡的不行，不知道你有这个问题吗？

**Comment by TheThreeDog** [comment]
> > 心态炸了。搞了个一模一样的Ubuntu虚拟机装上新的都能使了，我本机就是不行。
> > ----------结贴-----------
> > 已解决：
> > https://blog.csdn.net/Three_dog/article/details/103017873
> 
> 我的可以安装上，但是卡的不行，不知道你有这个问题吗？

卡倒是没有，崩溃是有的。比之前的版本稳定性差点，不过不管咋说比腾讯自己家的强太多了。
