### ISSUE TITLE
微信登陆后有一个窗口无法关掉

### ISSUE THREAD

**Issue by XinzheTing** [wszqkzqk/deepin-wine-ubuntu#207]
登录微信后除了一个主窗口外还有一个ChatContactMenu的窗口，始终无法关掉。

**Comment by quanbisen** [comment]
这个可以通过脚本去除，具体的帖子我忘记在哪里了，哪位大哥写的的也忘记了，需要安装xdotool，脚本是使用xdotool关闭那个窗口的。
安装xdotool(Ubuntu)：sudo apt install xdotool
脚本文件run1.sh
#!/bin/bash

"/opt/deepinwine/apps/Deepin-WeChat/run.sh">/dev/null 2>&1

start_succ=false

for i in {1..5}
do
	xdotool search --onlyvisible --classname "WeChat.exe"
	if [ $? == 0 ]
	then
		start_succ=true
		break
	fi
	sleep 10
done

if [ $start_succ == false ]
then
	exit 1
fi

windowclose=false

while :
do
	retval=$(xdotool search --onlyvisible --classname "WeChat.exe")
	
	if [ $? != 0 ]
	then
		exit 0
	fi
	
	login=true
	
	for id in $retval
	do
		windowname=$(xdotool getwindowname $id)
		if [ "$windowname" == "登录" ]
		then
			login=false
		fi
		
		if [ $windowclose == true ] && ([ "$windowname" == "" ] || [ "$windowname" == "ChatContactMenu" ])
		then
			xdotool windowclose $id
		fi
	done
	
	if [ $windowclose == true ]
	then
		exit 0
	fi
	
	if [ $login == true ]
	then
		windowclose=true
	fi
	
	sleep 2
done
最后修改/usr/share/applications/deepin.com.wechat.desktop文件，具体为Exec那行修改为上面的脚本文件路径。（注意：一定要安装xdotool，不然没效果）

**Comment by XinzheTing** [comment]
这所有的代码都是run1.sh里面的吗？我运行时出现“./run1.sh: line 51: syntax error: unexpected end of file
”

**Comment by XinzheTing** [comment]
非常感谢，我弄好了。这个代码贴的格式有些问题，应该从#!/bin/bash到done全部复制到run1.sh，它却被分成了三部分，最后那个done没复制进去……

**Comment by quanbisen** [comment]
对的，我复制了，而弄了几次，还是这样被划分的。。。有点奇怪。

**Comment by ghostry** [comment]
> 对的，我复制了，而弄了几次，还是这样被划分的。。。有点奇怪。

使用 ` 符号包围代码,开头放三个换行,结尾换行后放三个.就可以了.

**Comment by quanbisen** [comment]
> > 对的，我复制了，而弄了几次，还是这样被划分的。。。有点奇怪。
> 
> 使用 ` 符号包围代码,开头放三个换行,结尾换行后放三个.就可以了.

不行，不会用github呀。

**Comment by quanbisen** [comment]
> > 对的，我复制了，而弄了几次，还是这样被划分的。。。有点奇怪。
> 
> 使用 ` 符号包围代码,开头放三个换行,结尾换行后放三个.就可以了.

哇，可以了。

**Comment by ghostry** [comment]
> > > 对的，我复制了，而弄了几次，还是这样被划分的。。。有点奇怪。
> > 
> > 
> > 使用 ` 符号包围代码,开头放三个换行,结尾换行后放三个.就可以了.
> 
> 哇，可以了。

github用的Markdown语法,可以学一下.挺简单的.
