### ISSUE TITLE
不明白为什么，突然微信打不开了，重装也不行

### ISSUE THREAD

**Issue by Ranglage** [wszqkzqk/deepin-wine-ubuntu#216]
重启，重装都不行，我这生产环境的电脑不能重装系统啊？

**Comment by Ranglage** [comment]
htop里有微信在运行，然而看不到。

**Comment by SillyBorz** [comment]
我也出了这个问题，请问你解决了吗

**Comment by SillyBorz** [comment]
已解决，找到WeChat.exe, 然后通过 deepin-wine WeChat.exe 成功运行

**Comment by zhenyouliu** [comment]
能指导一下如何找到WeChat.exe吗

**Comment by oneLOH** [comment]
可以试下把/home/xxxx/.deepinwine/Deepin-WeChat目录删除再重装

**Comment by DandelionFs** [comment]
我的情况更诡异.
用 deepin 运行后报了个错误: 
`wine: '/home/xxx/.wine' is a 64-bit installation, it cannot be used with a 32-bit wineserver.`
之后用 wine 运行Wechat.exe成功...
