### ISSUE TITLE
Deepin-TIM、QQ无法加载图片和头像

### ISSUE THREAD

**Issue by RigoLigoRLC** [wszqkzqk/deepin-wine-ubuntu#222]
在Kubuntu 18.04 LTS上测试使用最新版Release安装Deepin-Wine，使用Deepin最新的QQ、TIM deb包安装，无法加载群聊中接收的绝大部分图片（手机发送的收藏表情除外）。更新容器内的软件无果。

**Comment by yunxia99** [comment]
+1

**Comment by b1oodgemini** [comment]
Ubuntu上也有这个问题,但是略有不同,刚打开的几分钟内(具体是多久没去测)是可以加载聊天图片的,之后所有的聊天图片就都加载失败

**Comment by love320** [comment]
本人长期使用WINE+TIM多年,群图一直接收正常.最近几十天出现群图片问题,现象是:登录成功后,大概15分~30分钟内群接收图片正常.之后就会出现无法接收图片. 感觉是本机的TIM出问题了,换QQ8.9试试, 发现有同样的问题,本人猜测可以是这样的. 登录成功后能正常使用群图片->说明在网络正常的情况是可用的. 大概15~30分钟后,出现群图片问题,但其它功能正常(接收文件\发信息)->大概可以猜测是非本机问题,可能是网络另端出问题(QQ服务器). 如果长期群图片接收问题解决不了,本人打算使用Linux-QQ(可能是QQ公司希望看到了).

**Comment by RigoLigoRLC** [comment]
昨天尝试把系统升级Kubuntu19.04，仍未解决。使用Tim2.3.2，仍不能正常使用。

**Comment by yuexiangqianlong** [comment]
我的也无法加载 也是几天前出现的问题

**Comment by RigoLigoRLC** [comment]
不知道deepin原生用户有没有遇到这种问题的？我暂时没时间测试。

**Comment by Neugls** [comment]
同ubuntu 18.04 无法接收图片

**Comment by zq1997** [comment]
关闭ipv6试试？？

**Comment by yuexiangqianlong** [comment]
我觉得是qq想让我们用Linux-QQ ，Linux-QQ发布时间：2019/10/24 时间和正好吻合qq图片不能用的为题， 如果没有解决办法的话我就换了

**Comment by zq1997** [comment]
官方的Linux-QQ 就是出来搞笑的，估计以后也不会更新

**Comment by yuexiangqianlong** [comment]
确实是搞笑的，5 6年前的

**Comment by RigoLigoRLC** [comment]
deepin公司服务器上的wine包已经比本repo的新了，今晚试试更新下包，看看有没有用，可以的话我就发个pr

**Comment by RigoLigoRLC** [comment]
经测试，安装Deepin的3.0Wine文件不能解决问题;同时本人的Manjaro笔记本上面2.18的Wine并没有加载图片出错的问题。

**Comment by yuexiangqianlong** [comment]
不行呀， 图就是加载不出来， 系统是 ubuntu 18.04

**Comment by yuexiangqianlong** [comment]
难道是防火墙的问题吗

**Comment by SillyBorz** [comment]
同这个问题

**Comment by linyingx** [comment]
同这个问题， 而且在群里聊天， 连着的两条信息， 发一样的图片， 一条能显示， 一条不能显示。

**Comment by RigoLigoRLC** [comment]
> 
> 
> 难道是防火墙的问题吗

不可能是，群里manjaro的用户们从AUR上编译的deepin wine的tim好像都没有问题

**Comment by yuexiangqianlong** [comment]
不是防火墙的问题， 还是qq服务器的问题， 自从有了 Linux-QQ就出现这个问题了

**Comment by TSwiftie** [comment]
我的头像能显示，但是不是最新的

**Comment by b1oodgemini** [comment]
从今天下午开始,似乎又能正常收到图片了

**Comment by b1oodgemini** [comment]
> Ubuntu上也有这个问题,但是略有不同,刚打开的几分钟内(具体是多久没去测)是可以加载聊天图片的,之后所有的聊天图片就都加载失败

从今天下午开始,似乎又可以正常收到图片了,几点开始的没注意,反正应该超过1小时了

**Comment by yuexiangqianlong** [comment]
我的也好了

**Comment by yuexiangqianlong** [comment]
不能夸，我的有不行了前 5秒还可以呢

**Comment by RigoLigoRLC** [comment]
今天凌晨1点测试结果显示，我这里仍然无法加载图片。

**Comment by RigoLigoRLC** [comment]
> 
> 
> 不能夸，我的有不行了前 5秒还可以呢

在任何设备上都从未接收国，且QQ在刚刚登陆时缓存下来的消息中含有的图片是可以查看到的。一旦消息在其他设备接收过，或者需要向上滚动以从服务器获取消息，那么该图片就不能被加载。

**Comment by yuexiangqianlong** [comment]
有没有好用的qq能加载图的， 系统是ubuntu 18.04

**Comment by crab-in-the-northeast** [comment]
现在电脑发出的图片文件加载没问题，其他都有问题qwq

**Comment by johncyuan** [comment]
可以试试在登录界面进入设置，设置网络

**Comment by BlindingDark** [comment]
> 可以试试在登录界面进入设置，设置网络

设置了本地 http 代理，目前可以了。再观察几天看看。

**Comment by yuexiangqianlong** [comment]
> > 可以试试在登录界面进入设置，设置网络
> 
> 设置了本地 http 代理，目前可以了。再观察几天看看。

就是走自己的服务器吗， 和vps一样吗

**Comment by johncyuan** [comment]
发现只要设置了可用代理，在直连模式下也可以收到图片

**Comment by yuexiangqianlong** [comment]
我试试

**Comment by yuexiangqianlong** [comment]
有点延迟，不过比没有强

**Comment by love320** [comment]
已经半个多月使用手机查看图片,现在设置代理能看到图片,太好了.

**Comment by b1oodgemini** [comment]
> 已经半个多月使用手机查看图片,现在设置代理能看到图片,太好了.



> 有点延迟，不过比没有强

有没有大佬给一个详细点的解决方案

**Comment by love320** [comment]
网上找的设置代理 -> https://blog.csdn.net/majiangnb/article/details/82984476
代理服务器,可以使用. -> http://www.ccproxy.com/

[本人不是打广告的]

**Comment by IceZero610** [comment]
设置代理之后可以正常加载，感谢各位！
自己有VPS的话可以用squid自己搭，我参考这位的：http://blog.haoji.me/linux-squid-reverse-proxy.html
其他情况也可以使用其他公用的服务器，可以参考楼上的链接

**Comment by RigoLigoRLC** [comment]
插一句，我10月份装的manjaro的笔记本可以正常接收。周末尝试将其Tencent Files文件夹覆盖问题电脑，得到解决。大家可以试试看备份Tencent Files文件夹后将源文件夹删除，设置代理连接并使用代理正常接收图片后将代理关闭，看看能不能解决问题。

**Comment by yuexiangqianlong** [comment]
> 插一句，我10月份装的manjaro的笔记本可以正常接收。周末尝试将其Tencent Files文件夹覆盖问题电脑，得到解决。大家可以试试看备份Tencent Files文件夹后将源文件夹删除，设置代理连接并使用代理正常接收图片后将代理关闭，看看能不能解决问题。

有没有第一个吃螃蟹的

**Comment by RigoLigoRLC** [comment]
> 
> 
> 网上找的设置代理 -> https://blog.csdn.net/majiangnb/article/details/82984476
> 代理服务器,可以使用. -> http://www.ccproxy.com/
> 
> [本人不是打广告的]

可以试试弄一个单一freedom的v2ray出站配置随机启动驻留吗？

**Comment by w-milfoil** [comment]
设置了个腾讯云的代理 发现一样.... 难道要用阿里云？

**Comment by love320** [comment]
> > 网上找的设置代理 -> https://blog.csdn.net/majiangnb/article/details/82984476
> > 代理服务器,可以使用. -> http://www.ccproxy.com/
> > [本人不是打广告的]
> 
> 可以试试弄一个单一freedom的v2ray出站配置随机启动驻留吗？

专业，这样感觉非常安全可靠。

**Comment by w-milfoil** [comment]
设置了代理后 也一样 只能用几分钟， 切换一次可以用一会儿

**Comment by RigoLigoRLC** [comment]
说明代理解决不了问题啊……
如果你自己的头像无法加载，那么就说明还是不行。
需要有人试试能不能用win下正常的Tencent Files进行替换，因为我的就是用自己另一台笔记本上正常工作的tim的文件替换好的。

**Comment by yuexiangqianlong** [comment]
我的头像和 图片都能加载 系统 ubuntu 18.04 qq代理 SOCKS5 代理到本地端口1080 ，shadowsocks 代理local_port 1080  ====》不用代理还是加载不出来

**Comment by TSwiftie** [comment]
现在发现不只是图片不能刷新，而且文件也不能下载。。。

**Comment by fzhengx** [comment]
我反正暂时是放弃治疗了，轻聊版凑合着用用，tx真坑

**Comment by b1oodgemini** [comment]
在本地跑一个squid(vps上也可以,但是一般出方向带宽都很小,效果肯定没有本地好),设置好代理就可以正常了.我测了两天,所有图片都可以正常收到

**Comment by apoot9999** [comment]
> > 可以试试在登录界面进入设置，设置网络
> 
> 设置了本地 http 代理，目前可以了。再观察几天看看。

我用privoxy搞了本地代理，设了也可以了，谢谢大佬指点

**Comment by smartliby** [comment]
我的设置了squid或者privoxy本地代理，图片还是加载不了，头疼

**Comment by love320** [comment]
本地代理，使用时尽量使用内网IP.(192...或 10.1...)
不要使用127.0.0.1之类的IP.

**Comment by smartliby** [comment]
> 我的设置了squid或者privoxy本地代理，图片还是加载不了，头疼

不要使用127.0.0.1，使用内网ip如192.或者10.开头的，目前可以正常使用了

**Comment by smartliby** [comment]
> 本地代理，使用时尽量使用内网IP.(192...或 10.1...)
> 不要使用127.0.0.1之类的IP.

亲测好用

**Comment by liulianjun1995** [comment]
@smartliby 你用的squid还是privoxy？我用的squid在阿里云上和本地跑，能测试代理连接是OK的，但是还是加载不上来图片。

**Comment by smartliby** [comment]
> @smartliby 你用的squid还是privoxy？我用的squid在阿里云上和本地跑，能测试代理连接是OK的，但是还是加载不上来图片。

privoxy，本地代理，不要使用127.0.0.1之类的IP

**Comment by liulianjun1995** [comment]
@smartliby 老哥咋配置的，我自己弄了弄还是不行

**Comment by smartliby** [comment]
> @smartliby 老哥咋配置的，我自己弄了弄还是不行

privoxy默认监听127.0.0.1，需要你手动改下配置 vim /etc/privoxy/config
将listen-address  127.0.0.1:8118改成listen-address  0.0.0.0:8118

**Comment by liulianjun1995** [comment]
@smartliby 感谢老哥，确实可以了！

**Comment by irezm** [comment]
> 关闭ipv6试试？？

感谢老歌，果然是 ipv6的问题，我用的是软路由，是那种集体租房，宽带是房东弄得，设备都很老了，不支持ipv6，软路由内置ipv6无网，我就说使用这么久时间突然就无法查看图片了

**Comment by XuCpeng** [comment]
> 关闭ipv6试试？？

这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。

**Comment by b1oodgemini** [comment]
> > 关闭ipv6试试？？
> 
> 这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。

我关掉代理关掉ipv6并收不到图片

**Comment by XuCpeng** [comment]
> > > 关闭ipv6试试？？
> > 
> > 
> > 这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。
> 
> 我关掉代理关掉ipv6并收不到图片

关闭ipv6之后还收不到应该是因为旧缓存的原因，`rm -rf ~/.deepinwine/Deepin-TIM`，然后重新打开即可。

**Comment by BlindingDark** [comment]
> 这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。

这样所有连接都无法使用 ipv6 了，不知道能不能单独针对某个应用设置。

**Comment by XuCpeng** [comment]
> > 这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。
> 
> 这样所有连接都无法使用 ipv6 了，不知道能不能单独针对某个应用设置。

我的今天又不行了，关闭ipv6也没用

**Comment by ihipop** [comment]
> > > 这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。
> > 
> > 
> > 这样所有连接都无法使用 ipv6 了，不知道能不能单独针对某个应用设置。
> 
> 我的今天又不行了，关闭ipv6也没用

和代理没关系，用代理好只是因为歪打正着

真正的原因是最近腾讯不知道改了什么，可能集体迁移过机房，网络环境有变化，如果你的mtu值不合适，加载图片的服务你就访问不了，你可以通过如下方式验证：

**如果你的QQ的消息图片加载不出来，尝试访问一下QQ的一些网站，比如tim的页面，QQ的下载页面，如果打开也很慢，转半天，请你更改你机器的MTU设置，我改成1412好了**

我是看到这个帖子了https://bbs.deepin.org/forum.php?mod=viewthread&tid=188184 一开始我以为这个帖子是扯淡，腾讯怎么会发生这种低级情况，试了一下真的可以。。。腾讯的基础设施机房不知道搞什么技术创新了又。。。

**Comment by QRQaccount** [comment]
> > > > 关闭ipv6试试？？
> > > 
> > > 
> > > 这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。
> > 
> > 
> > 我关掉代理关掉ipv6并收不到图片
> 
> 关闭ipv6之后还收不到应该是因为旧缓存的原因，`rm -rf ~/.deepinwine/Deepin-TIM`，然后重新打开即可。
manjaro系统，删除旧缓存后聊天图片正常加载了，但是头像显示还是有问题:-)

**Comment by jeasonlau** [comment]
> > > 这是正确的原因及方法，挂代理不过是曲线救国，将本机的网络配置中的ipv6连接“关闭”或者“忽略”即可。
> > 
> > 
> > 这样所有连接都无法使用 ipv6 了，不知道能不能单独针对某个应用设置。
> 
> 我的今天又不行了，关闭ipv6也没用

同样，只有第一次有用..

**Comment by wtdcode** [comment]
我觉得关键是这句
```
[0216/210222:ERROR:network_change_notifier_win.cc(158)] WSALookupServiceBegin failed with: 8
```

**Comment by kdeplus** [comment]
有人开始有打不开聊天记录的情况吗？我最近聊天记录经常开不了，显示空白或者需要刷新

**Comment by Castleeee** [comment]
我也收不到图片,linux用户不配用QQ吗?

**Comment by jeasonlau** [comment]
> 我也收不到图片,linux用户不配用QQ吗?

如果实在整不好，只能用QQ for linux了（

**Comment by linrol** [comment]
关闭ipv6和用代理哪个更靠谱？

**Comment by lackboy741** [comment]
> @smartliby 感谢老哥，确实可以了！

请问是privoxy监听8118后，转发socks5的方式吗？

listen-address 127.0.0.1:8118  # privoxy监听8118端口
forward-socks5 / 127.0.0.1:1080

**Comment by zedpass** [comment]
> > @smartliby 感谢老哥，确实可以了！
> 
> 请问是privoxy监听8118后，转发socks5的方式吗？
> 
> listen-address 127.0.0.1:8118 # privoxy监听8118端口
> forward-socks5 / 127.0.0.1:1080
> 
> 这里有些搞不懂，请指教。谢谢。

关闭ipv6吧，一劳永逸，挂代理可能会不行

**Comment by lackboy741** [comment]
@zedpass 
谢谢回答。
有个疑问，ipv6关闭了，但是不行。
难道说是要关闭路由器的ipv6？

![ipv6](https://user-images.githubusercontent.com/17449274/76493317-534d2900-646d-11ea-99cb-55df3f028528.png)

**Comment by smartliby** [comment]
> > @smartliby 感谢老哥，确实可以了！
> 
> 请问是privoxy监听8118后，转发socks5的方式吗？
> 
> listen-address 127.0.0.1:8118 # privoxy监听8118端口
> forward-socks5 / 127.0.0.1:1080
> 
> 这里有些搞不懂，请指教。谢谢。

在qq上直接设置http代理就行了,不需要socks5

**Comment by zedpass** [comment]
> @zedpass
> 谢谢回答。
> 有个疑问，ipv6关闭了，但是不行。
> 难道说是要关闭路由器的ipv6？
> 
> ![ipv6](https://user-images.githubusercontent.com/17449274/76493317-534d2900-646d-11ea-99cb-55df3f028528.png)

你用grub关闭ipv6试试？deepin和manjaro关闭都可以，ubuntu理论上应该也是一样的问题

**Comment by RigoLigoRLC** [comment]
经本人长期实测，关闭IPv6在本人三台计算机上绝大部分情况下无效（Manjaro KDE 19.0 / Linux 5.5），在将QQ连接至V2Ray后再未出现过无法接收图片的问题。建议大家使用Squid解决该问题。已有梯子的，可以直接连接到梯子的客户端上，给腾讯的服务器设置白名单，就可绕过梯子而只使用代理转发的功能。

**Comment by taotieren** [comment]
> 经本人长期实测，关闭IPv6在本人三台计算机上绝大部分情况下无效（Manjaro KDE 19.0 / Linux 5.5），在将QQ连接至V2Ray后再未出现过无法接收图片的问题。建议大家使用Squid解决该问题。已有梯子的，可以直接连接到梯子的客户端上，给腾讯的服务器设置白名单，就可绕过梯子而只使用代理转发的功能。

最近测试还是时好时坏的
万人血书给腾讯催更新 QQ for Linux 吗

**Comment by RigoLigoRLC** [comment]
> 最近测试还是时好时坏的
> 万人血书给腾讯催更新 QQ for Linux 吗

要发起不是不可以，我觉得用户群还是太少，影响力目前可能说起来不是那么大

**Comment by lackboy741** [comment]
@zedpass 

谢谢指教。十分感谢。

通过grub方式关闭ipv6后，qq和微信收发图片和文件都正常了。

有需要的朋友可以参考这里。
[关闭IPV6的方式](https://www.cnblogs.com/minseo/p/10223546.html)

**Comment by taotieren** [comment]
@lackboy741 可是不想关 IPv6 因为有分配到 IP v6 的地址。还有别的方式吗？

**Comment by myl7** [comment]
为 QQ 用 provixy 配置了一个 HTTP 代理后，我的图片显示和头像也正常

provixy 的配置是保证有一行：

```
listen-address [ip]:8118
```

且无转发，即没有 `forward-*` 之类的配置

`[ip]` 处我用的是 docker 设的 docker0 网卡的 IP，以保证不用 127.0.0.1 来指向本机

**Comment by Espylapiza** [comment]
只有UDP连接没有TCP的情况就会出现这个情况，我设置127.0.0.1是可以连接的

**Comment by taotieren** [comment]
顺手写一下 Manjaro Linux 关闭 IPv6 的方法

``` bash
sudo vim /etc/sysctl.d/99-disable_ipv6.conf
```
``` bash
# IPv6 disabled
net.ipv6.conf.all.disable_ipv6 =1
net.ipv6.conf.default.disable_ipv6 =1
net.ipv6.conf.lo.disable_ipv6 =1
```
``` bash
sudo sysctl -p --system 
```

``` bash
ifconfig -a
```

**Comment by wtdcode** [comment]
提供一个简易的转发方案。

直接用v2ray，下面贴一个实例配置

```json
{
  "inbounds" : [
    {
      "listen" : "127.0.0.1",
      "port" : 1099,
      "protocol" : "http",
      "tag" : "qq",
      "settings" : {
        "timeout" : 0
      }
    }
  ],
  "outbounds" : [
    {
            "protocol" : "freedom",
            "tag" : "direct"
    }
  ],
  "routing" : {
    "domainStrategy" : "AsIs",
    "rules" : [
      {
        "type" : "field",
        "inboundTag" : "qq",
        "outboundTag" : "direct"
      }
    ]
  }
}
```

然后QQ选择HTTP代理为 127.0.0.1:1099

在我KDE上那个下拉框出不来可以用键盘上下左右键来选择。

**Comment by MXWXZ** [comment]
如果已经有V2ray梯子的话还是用privoxy转发比较好
```
yay -S privoxy
sudo systemctl start privoxy.service
sudo systemctl enable privoxy.service
```
HTTP代理127.0.0.1:8118即可

**Comment by wimmerX** [comment]
本地搭建一级proxy服务，可以解决此问题。🏂🏂

**Comment by ihipop** [comment]
deepin今天发布了更新,不需要任何设置 直接可以加载图片头像了.应该还是deepin wine自己的问题?
现在可以去掉所有"魔法"设置直接使用了 没问题了

**Comment by taotieren** [comment]
有同步更新过来吗？2020年6月4日 13:43，ihipop <notifications@github.com>写道：

deepin今天发布了更新,不需要任何设置 直接可以加载图片头像了.应该还是deepin wine自己的问题?

现在可以去掉所有"魔法"设置直接使用了 没问题了

**Comment by taotieren** [comment]
Arch Linux 上的 AUR 的包有同步更新吗？2020年6月4日 14:48，admin@taotieren.com写道：有同步更新过来吗？2020年6月4日 13:43，ihipop <notifications@github.com>写道：

deepin今天发布了更新,不需要任何设置 直接可以加载图片头像了.应该还是deepin wine自己的问题?

现在可以去掉所有"魔法"设置直接使用了 没问题了

**Comment by RigoLigoRLC** [comment]
确实是wine自己对ipv6支持不善，deepin这次应该是修了这个问题。AUR包不知道，应该还没更新，不过可以自己改一下pkgbuild试试

**Comment by yylzcom** [comment]
Ubuntu 19.10
deepin-wine: 2.18

通过上面命令行禁用IPv6后问题解决

**Comment by xiaoke0O** [comment]
我开启了路由器的ipv6后解决了问题。系统没有禁ipv6

**Comment by CHN-STUDENT** [comment]
@wtdcode 感谢，**需要特别注意的是如果代理鼠标无法选择，可以用键盘按键进行选择。**

**Comment by AlliotTech** [comment]
privoxy正解。
