### ISSUE TITLE
QQ图片无法接收

### ISSUE THREAD

**Issue by aveyuan** [wszqkzqk/deepin-wine-ubuntu#225]
以前都是好好的，最近升级了wine
刚开始打开的时候，图片还能接收，过一会儿，就接收不到了。
关闭QQ,打开控制台发现，过了一会儿出现txupd.exe找不到的情况。
```
 wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\txupd.exe"
wine: cannot find L"c:\\Program Files\\Tencent\\QQ\\txupd.exe"
```

Wine版本
```
 wine --version
wine-4.0
```

**Comment by irezm** [comment]
有lssues了，禁用本机的ipv6，删除掉QQ缓存文件聊天记录不用删

**Comment by aveyuan** [comment]
> 有lssues了，替换本机的ipv6，删除掉QQ缓存文件聊天记录不用删除

不行的，试过好几次了，哎，是tx的问题，以前都是好的，一直没升级。突然就这样了。

**Comment by SpringHan** [comment]
安装privoxy，启动后在QQ登录界面进入设置，选择http代理，填写IP地址和监听端口，然后检测能否连接代理服务器，如果连接成功，再登录即可显示图片。若要刷新QQ头像，就删除~/.deepinwine文件夹再重启QQ即可
本人Arch用户亲测有用

**Comment by aveyuan** [comment]
> 安装privoxy，启动后在QQ登录界面进入设置，选择http代理，填写IP地址和监听端口，然后检测能否连接代理服务器，如果连接成功，再登录即可显示图片。若要刷新QQ头像，就删除~/.deepinwine文件夹再重启QQ即可
> 本人Arch用户亲测有用

有效，谢谢

**Comment by shawnust** [comment]
> 安装privoxy，启动后在QQ登录界面进入设置，选择http代理，填写IP地址和监听端口，然后检测能否连接代理服务器，如果连接成功，再登录即可显示图片。若要刷新QQ头像，就删除~/.deepinwine文件夹再重启QQ即可
> 本人Arch用户亲测有用

为什么我的QQ登陆界面进去的网络设置的代理各种按钮菜单都是灰色的，没法点。我的QQ是9.1.8，ubuntu 16.04。
