### ISSUE TITLE
QQ和微信同时打开，QQ就不能加载图片

### ISSUE THREAD

**Issue by dafeinayius** [wszqkzqk/deepin-wine-ubuntu#226]
如题，我使用Archlinux KDE版本，同时使用QQ和微信，就会出现QQ加载不出图片的情况，一直在转。但是只开QQ就可以正常接收图片。有人有类似的情况吗？

**Comment by lackboy741** [comment]
你是怎么解决的呀

**Comment by lackboy741** [comment]
@dafeinayius  你是怎么解决的？

**Comment by ilittlemoe** [comment]
> @dafeinayius 你是怎么解决的？

https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/222 解决方案

希望能帮助到你
