### ISSUE TITLE
关于QQ轻聊和tim均不显示托盘的问题

### ISSUE THREAD

**Issue by DockerYumeko** [wszqkzqk/deepin-wine-ubuntu#227]
环境是ubuntu19.04，安装了top icon plus，但是QQ和微信仍旧不显示托盘图标，有大佬知道怎么解决吗

**Comment by liulianjun1995** [comment]
去github下载top icon plus安装

**Comment by HyperClockUp** [comment]
> 去github下载top icon plus安装

仍然无效

**Comment by CodingOctocat** [comment]
> 去github下载top icon plus安装

注意审题，人家已经安装了 topicon plus。

**Comment by liulianjun1995** [comment]
@CodingOctocat 源码编译安装能解决，在商店或者https://extensions.gnome.org/安装就会出现这种情况

**Comment by DockerYumeko** [comment]
> @CodingOctocat 源码编译安装能解决，在商店或者[https://extensions.gnome.org/安装就会出现这种情况](https://extensions.gnome.org/%E5%AE%89%E8%A3%85%E5%B0%B1%E4%BC%9A%E5%87%BA%E7%8E%B0%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5)

编译top icon plus的源码么

**Comment by liulianjun1995** [comment]
@DockerYumeko  对

**Comment by DockerYumeko** [comment]
> @DockerYumeko 对

好的，我去看看，谢谢
