### ISSUE TITLE
Ubuntu 19.10 安装了 Topicon plus 还是没有托盘，关闭微信就消失了，但进程还在

### ISSUE THREAD

**Issue by CodingOctocat** [wszqkzqk/deepin-wine-ubuntu#228]
我安装了 Topicon plus，wine 的图标成功隐藏了，但如果关闭 微信或者迅雷，那么表面上关闭了，实际进程还在后台，而且没有托盘！

**Comment by sherlockwho** [comment]
把 topicons plus 改成 topicons plus git

**Comment by KenMizz** [comment]
@CodingOctocat https://extensions.gnome.org/extension/2311/topicons-plus/
安装TopIcons Plus Git来解决问题
![image](https://user-images.githubusercontent.com/16635884/75987464-f62a0400-5ebd-11ea-9284-2a7f3f0bd5ef.png)

**Comment by CodingOctocat** [comment]
> @CodingOctocat https://extensions.gnome.org/extension/2311/topicons-plus/
> 安装TopIcons Plus Git来解决问题
> ![图片](https://user-images.githubusercontent.com/16635884/75987464-f62a0400-5ebd-11ea-9284-2a7f3f0bd5ef.png)

我想应该找到答案，可能需要自己编译该扩展：https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/227#issuecomment-571659268
