### ISSUE TITLE
中文字体的问题

### ISSUE THREAD

**Issue by KenMizz** [wszqkzqk/deepin-wine-ubuntu#242]
我在Pop!_os 19.10上运行的这个库
我的中文字体是这样的
![截屏-20200229171938-968x414.png](https://i.loli.net/2020/03/01/p5c4XNO2UjVAE6T.png)
请问一下有什么办法解决吗

**Comment by sherlockwho** [comment]
这个中文字体有什么异常吗？不是能正常显示吗

**Comment by KenMizz** [comment]
@sherlockwho 字体十分的端正，我想找个方法更换字体..

**Comment by sherlockwho** [comment]
@KenMizz 试试这样有没有用
gedit ~/.deepinwine/Deepin-WeChat/system.reg
在其中找到下面两行进行编辑
"MS Shell Dlg"=" "
"MS Shell Dlg 2"=" "

**Comment by KenMizz** [comment]
@sherlockwho 
![image](https://user-images.githubusercontent.com/16635884/75937247-5daa6a00-5e52-11ea-93d4-3e8b8ae1c789.png)好了，多谢老哥
