### ISSUE TITLE
QQ安装微软雅黑字体 部分界面显示黑框

### ISSUE THREAD

**Issue by kevinMintnick** [wszqkzqk/deepin-wine-ubuntu#244]
![屏幕截图](https://user-images.githubusercontent.com/53930316/76676707-347f9b80-6601-11ea-85fa-5a4bbfffb838.png)
![屏幕截图_1](https://user-images.githubusercontent.com/53930316/76676730-4b25f280-6601-11ea-871a-c08219b4702e.png)

**Comment by wszqkzqk** [comment]
暂时字体支持确实不太好，尤其是中文显示，能用的自体不多
