### ISSUE TITLE
TIM QQ 用户头像无法正常显示，群头像可以显示，请问大佬如何解决

### ISSUE THREAD

**Issue by LaureatePoet** [wszqkzqk/deepin-wine-ubuntu#249]
如图
![用户头像无法显示](https://s1.ax1x.com/2020/03/21/8fHUHS.png)

另外希望推荐一些TIM的字体

环境：**Ubuntu 18.04.3 LTS**

**Comment by xelll** [comment]
据说关掉IPV6或者设置qq使用代理。

**Comment by yoy-aww** [comment]
我使用的TIM.      关闭IPV6, 头像仍然显示不正常.
代理的话, 我无法配置. 因为TIM的网络设置的类型下拉选择框, 根本不能下拉选择.
默认只能是'不使用代理'

**Comment by yoy-aww** [comment]
再次提问, 我的TIM, 选择网络设置的类型选项, 无法打开可选项。请问, 其他用户可以设置网络设置吗？
可以设置的用户，你们的tim包, 是哪个版本？
