### ISSUE TITLE
mint托盘图标失效

### ISSUE THREAD

**Issue by zq-97** [wszqkzqk/deepin-wine-ubuntu#29]
linux mint 19
Cinnamon 3.8.9桌面环境
TIM和百度云，使用正常，托盘图标也能显示，不过过一段时间（几分钟到几个小时不一定），托盘图标就无法响应点击、甚至直接变黑消失了。
是缺少什么配置吗？

**Comment by wszqkzqk** [comment]
暂时不知道问题在哪里

**Comment by duaneya** [comment]
你的能用搜狗输入法吗

**Comment by zq-97** [comment]
@duaneya 可以用

**Comment by zq-97** [comment]
@wszqkzqk 话说托盘图标失效的复现条件我找到了：外接双屏。单屏的时候一切正常

**Comment by sishuai** [comment]
@zq-97 
> @wszqkzqk 话说托盘图标失效的复现条件我找到了：外接双屏。单屏的时候一切正常

这个bug是在主屏的位置起始点不是(0,0)的时候才会出现【主屏在最左侧没问题】，这个时候点击不了托盘图标

原始帖见 https://bbs.deepin.org/forum.php?mod=viewthread&tid=155949

临时可以用https://bbs.deepin.org/forum.php?mod=viewthread&tid=155949 中5楼的附件替换下shell32.dll.so文件，sudo cp shell32.dll.so /usr/lib/i386-linux-gnu/deepin-wine/

**Comment by zq-97** [comment]
我刚试了一下，在左边也是一样的，不知道 缘故

**Comment by sishuai** [comment]
@zq-97 

> 我刚试了一下，在左边也是一样的，不知道 缘故

可以把左侧的设置为主屏幕，然后注销Ubuntu账号，然后重新登录试试

**Comment by zq-97** [comment]
注销了一下，也是不行，我明天看看重启行不行

**Comment by sishuai** [comment]
> 注销了一下，也是不行，我明天看看重启行不行

恩恩，也可能和我的不是一个问题导致的

**Comment by zq-97** [comment]
还是不行，看来这个方法对mint行不通

**Comment by zq-97** [comment]
@sishuai 再次验证，你说的左边设置为主屏是有效的！
我今天才发现，我的左边屏幕竟然有几个像素的偏移，导致之前左边的坐标表示从原点开始。
其他有这个问题的同学不妨也xrand确认一下左边屏幕的坐标。
