### ISSUE TITLE
很多容器不能运行，包括CajViewer等实用的工具

### ISSUE THREAD

**Issue by leixd1994** [wszqkzqk/deepin-wine-ubuntu#3]

**Comment by wszqkzqk** [comment]
这个是什么容器？deepin官方打包了吗？

**Comment by leixd1994** [comment]
这个是中国知网Caj格式论文的阅读器  容器的那个网址里面有  
![screenshot from 2018-07-08 10-13-48](https://user-images.githubusercontent.com/23328517/42416072-a502d77c-8297-11e8-8af3-d6d3c3c8bfbe.png)
@wszqkzqk

**Comment by wszqkzqk** [comment]
这个命名都是旧版应用。

**Comment by wszqkzqk** [comment]
新版deepinwine都是deepin.xxx.xxx
