### ISSUE TITLE
卸载时候报错Unable to locate package

### ISSUE THREAD

**Issue by ArkiZh** [wszqkzqk/deepin-wine-ubuntu#307]
执行./uninstall.sh时候报错如下，请问有解决方法吗：

> 
> 正在准备卸载...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package 1.2deepin-fonts-wine_2.18-12_all.deb
> E: Unable to locate package 2.1deepin-libwine_2.18-12_i386.deb
> E: Unable to locate package 2.2deepin-libwine-dbg_2.18-12_i386.deb
> E: Unable to locate package 2.3deepin-libwine-dev_2.18-12_i386.deb
> E: Unable to locate package 3.1deepin-wine32_2.18-12_i386.deb
> E: Unable to locate package 3.2deepin-wine32-preloader_2.18-12_i386.deb
> E: Unable to locate package 3.3deepin-wine32-tools_2.18-12_i386.deb
> E: Unable to locate package 3.4deepin-wine32-preloader_2.18-12_i386.deb
> E: Unable to locate package 4deepin-wine_2.18-12_all.deb
> E: Unable to locate package 5deepin-wine-binfmt_2.18-12_all.deb
> E: Unable to locate package 6.1deepin-wine-plugin_1.0deepin2_amd64.deb
> E: Unable to locate package 6.2deepin-wine-plugin-virtual_1.0deepin1_all.deb
> E: Unable to locate package 7deepin-wine-helper_1.2deepin8_i386.deb
> E: Unable to locate package 8deepin-wine-uninstaller_0.1deepin2_i386.deb
> E: Unable to locate package deepin-fonts-wine_2.18-12_all
> E: Unable to locate package deepin-libwine_2.18-12_i386
> E: Unable to locate package deepin-libwine-dbg_2.18-12_i386
> E: Unable to locate package deepin-libwine-dev_2.18-12_i386
> E: Unable to locate package deepin-wine_2.18-12_all
> E: Unable to locate package deepin-wine_2.18-12_all.deb
> E: Unable to locate package deepin-wine32_2.18-12_i386
> E: Unable to locate package deepin-wine32-preloader_2.18-12_i386
> E: Unable to locate package deepin-wine32-tools_2.18-12_i386
> E: Unable to locate package deepin-wine-binfmt_2.18-12_all
> E: Unable to locate package deepin-wine-helper_1.2deepin8_i386
> E: Unable to locate package deepin-wine-plugin_1.0deepin2_amd64
> E: Unable to locate package deepin-wine-plugin-virtual_1.0deepin1_all
> E: Unable to locate package deepin-wine-uninstaller_0.1deepin2_i386
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 卸载完成...

之后查看package时候如下：

> dpkg -l | grep deepin
> ii  deepin-fonts-wine                          2.18-12                               all          Windows API implementation - fonts
> ii  deepin-libwine:i386                        2.18-12                               i386         Windows API implementation - library
> ii  deepin-libwine-dbg:i386                    2.18-12                               i386         Windows API implementation - debugging symbols
> ii  deepin-libwine-dev:i386                    2.18-12                               i386         Windows API implementation - development files
> ii  deepin-wine                                2.18-12                               all          Windows API implementation - standard suite
> ii  deepin-wine-binfmt                         2.18-12                               all          Windows API implementation - binfmt support
> ii  deepin-wine-helper:i386                    1.2deepin8                            i386         Deepin Wine Helper
> ii  deepin-wine-plugin                         1.0deepin2                            amd64        Deepin Wine plugin
> ii  deepin-wine-plugin-virtual                 1.0deepin1                            all          Deepin Wine plugin virtual package
> ii  deepin-wine-uninstaller:i386               0.1deepin2                            i386         Deepin Wine Uninstaller Tool
> ii  deepin-wine32:i386                         2.18-12                               i386         Windows API implementation - 32-bit binary loader
> ii  deepin-wine32-preloader:i386               2.18-12                               i386         Windows API implementation - prelinked 32-bit binary loader
> ii  deepin-wine32-tools:i386                   2.18-12                               i386         Windows API implementation - 32-bit developer tools

执行apt卸载命令也报错：

> sudo apt purge deepin*
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package deepin-fonts-wine_2.18-12_all
> E: Unable to locate package deepin-libwine_2.18-12_i386
> E: Unable to locate package deepin-libwine-dbg_2.18-12_i386
> E: Unable to locate package deepin-libwine-dev_2.18-12_i386
> E: Unable to locate package deepin-wine_2.18-12_all
> E: Unable to locate package deepin-wine_2.18-12_all.deb
> E: Unable to locate package deepin-wine32_2.18-12_i386
> E: Unable to locate package deepin-wine32-preloader_2.18-12_i386
> E: Unable to locate package deepin-wine32-tools_2.18-12_i386
> E: Unable to locate package deepin-wine-binfmt_2.18-12_all
> E: Unable to locate package deepin-wine-helper_1.2deepin8_i386
> E: Unable to locate package deepin-wine-plugin_1.0deepin2_amd64
> E: Unable to locate package deepin-wine-plugin-virtual_1.0deepin1_all
> E: Unable to locate package deepin-wine-uninstaller_0.1deepin2_i386
> 

重新安装后再执行卸载还是这些报错。

**Comment by FaithALL** [comment]
sudo apt-get purge \*deepin\*wine\* udis86
sudo apt autopurge
rm -r ~/.deepinwine/

新版的apt remove/purge 为了安全**好像**禁掉了通配符，使用apt-get就没问题

**Comment by peacemo** [comment]
@FaithALL 还是有问题
正在准备卸载...
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 1.2deepin-fonts-wine_2.18-12_all.deb
E: 无法按照 glob ‘1.2deepin-fonts-wine_2.18-12_all.deb’ 找到任何软件包
E: 无法按照正则表达式 1.2deepin-fonts-wine_2.18-12_all.deb 找到任何软件包
E: 无法定位软件包 2.1deepin-libwine_2.18-12_i386.deb
E: 无法按照 glob ‘2.1deepin-libwine_2.18-12_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 2.1deepin-libwine_2.18-12_i386.deb 找到任何软件包
E: 无法定位软件包 2.2deepin-libwine-dbg_2.18-12_i386.deb
E: 无法按照 glob ‘2.2deepin-libwine-dbg_2.18-12_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 2.2deepin-libwine-dbg_2.18-12_i386.deb 找到任何软件包
E: 无法定位软件包 2.3deepin-libwine-dev_2.18-12_i386.deb
E: 无法按照 glob ‘2.3deepin-libwine-dev_2.18-12_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 2.3deepin-libwine-dev_2.18-12_i386.deb 找到任何软件包
E: 无法定位软件包 3.1deepin-wine32_2.18-12_i386.deb
E: 无法按照 glob ‘3.1deepin-wine32_2.18-12_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 3.1deepin-wine32_2.18-12_i386.deb 找到任何软件包
E: 无法定位软件包 3.2deepin-wine32-preloader_2.18-12_i386.deb
E: 无法按照 glob ‘3.2deepin-wine32-preloader_2.18-12_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 3.2deepin-wine32-preloader_2.18-12_i386.deb 找到任何软件包
E: 无法定位软件包 3.3deepin-wine32-tools_2.18-12_i386.deb
E: 无法按照 glob ‘3.3deepin-wine32-tools_2.18-12_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 3.3deepin-wine32-tools_2.18-12_i386.deb 找到任何软件包
E: 无法定位软件包 3.4deepin-wine32-preloader_2.18-12_i386.deb
E: 无法按照 glob ‘3.4deepin-wine32-preloader_2.18-12_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 3.4deepin-wine32-preloader_2.18-12_i386.deb 找到任何软件包
E: 无法定位软件包 4deepin-wine_2.18-12_all.deb
E: 无法按照 glob ‘4deepin-wine_2.18-12_all.deb’ 找到任何软件包
E: 无法按照正则表达式 4deepin-wine_2.18-12_all.deb 找到任何软件包
E: 无法定位软件包 5deepin-wine-binfmt_2.18-12_all.deb
E: 无法按照 glob ‘5deepin-wine-binfmt_2.18-12_all.deb’ 找到任何软件包
E: 无法按照正则表达式 5deepin-wine-binfmt_2.18-12_all.deb 找到任何软件包
E: 无法定位软件包 6.1deepin-wine-plugin_1.0deepin2_amd64.deb
E: 无法按照 glob ‘6.1deepin-wine-plugin_1.0deepin2_amd64.deb’ 找到任何软件包
E: 无法按照正则表达式 6.1deepin-wine-plugin_1.0deepin2_amd64.deb 找到任何软件包
E: 无法定位软件包 6.2deepin-wine-plugin-virtual_1.0deepin1_all.deb
E: 无法按照 glob ‘6.2deepin-wine-plugin-virtual_1.0deepin1_all.deb’ 找到任何软件包
E: 无法按照正则表达式 6.2deepin-wine-plugin-virtual_1.0deepin1_all.deb 找到任何软件包
E: 无法定位软件包 7deepin-wine-helper_1.2deepin8_i386.deb
E: 无法按照 glob ‘7deepin-wine-helper_1.2deepin8_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 7deepin-wine-helper_1.2deepin8_i386.deb 找到任何软件包
E: 无法定位软件包 8deepin-wine-uninstaller_0.1deepin2_i386.deb
E: 无法按照 glob ‘8deepin-wine-uninstaller_0.1deepin2_i386.deb’ 找到任何软件包
E: 无法按照正则表达式 8deepin-wine-uninstaller_0.1deepin2_i386.deb 找到任何软件包
E: 无法定位软件包 deepin-fonts-wine_2.18-12_all
E: 无法按照 glob ‘deepin-fonts-wine_2.18-12_all’ 找到任何软件包
E: 无法按照正则表达式 deepin-fonts-wine_2.18-12_all 找到任何软件包
E: 无法定位软件包 deepin-libwine_2.18-12_i386
E: 无法按照 glob ‘deepin-libwine_2.18-12_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-libwine_2.18-12_i386 找到任何软件包
E: 无法定位软件包 deepin-libwine-dbg_2.18-12_i386
E: 无法按照 glob ‘deepin-libwine-dbg_2.18-12_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-libwine-dbg_2.18-12_i386 找到任何软件包
E: 无法定位软件包 deepin-libwine-dev_2.18-12_i386
E: 无法按照 glob ‘deepin-libwine-dev_2.18-12_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-libwine-dev_2.18-12_i386 找到任何软件包
E: 无法定位软件包 deepin-wine_2.18-12_all
E: 无法按照 glob ‘deepin-wine_2.18-12_all’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine_2.18-12_all 找到任何软件包
E: 无法定位软件包 deepin-wine_2.18-12_all.deb
E: 无法按照 glob ‘deepin-wine_2.18-12_all.deb’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine_2.18-12_all.deb 找到任何软件包
E: 无法定位软件包 deepin-wine32_2.18-12_i386
E: 无法按照 glob ‘deepin-wine32_2.18-12_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine32_2.18-12_i386 找到任何软件包
E: 无法定位软件包 deepin-wine32-preloader_2.18-12_i386
E: 无法按照 glob ‘deepin-wine32-preloader_2.18-12_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine32-preloader_2.18-12_i386 找到任何软件包
E: 无法定位软件包 deepin-wine32-tools_2.18-12_i386
E: 无法按照 glob ‘deepin-wine32-tools_2.18-12_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine32-tools_2.18-12_i386 找到任何软件包
E: 无法定位软件包 deepin-wine-binfmt_2.18-12_all
E: 无法按照 glob ‘deepin-wine-binfmt_2.18-12_all’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine-binfmt_2.18-12_all 找到任何软件包
E: 无法定位软件包 deepin-wine-helper_1.2deepin8_i386
E: 无法按照 glob ‘deepin-wine-helper_1.2deepin8_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine-helper_1.2deepin8_i386 找到任何软件包
E: 无法定位软件包 deepin-wine-plugin_1.0deepin2_amd64
E: 无法按照 glob ‘deepin-wine-plugin_1.0deepin2_amd64’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine-plugin_1.0deepin2_amd64 找到任何软件包
E: 无法定位软件包 deepin-wine-plugin-virtual_1.0deepin1_all
E: 无法按照 glob ‘deepin-wine-plugin-virtual_1.0deepin1_all’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine-plugin-virtual_1.0deepin1_all 找到任何软件包
E: 无法定位软件包 deepin-wine-uninstaller_0.1deepin2_i386
E: 无法按照 glob ‘deepin-wine-uninstaller_0.1deepin2_i386’ 找到任何软件包
E: 无法按照正则表达式 deepin-wine-uninstaller_0.1deepin2_i386 找到任何软件包
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。

**Comment by peacemo** [comment]
自己根据dpkg的包列表定位了一些deepin-wine相关的包，然后手动卸载。下面是命令，执行前务必仔细校对一下！！

```
dpkg -purge deepin-app-store deepin-fonts-wine deepin-libwine:i386 deepin-libwine-dbg:i386 deepin-libwine-dev:i386 deepin-notifications deepin-wine deepin-wine-binfmt deepin-wine-helper:i386 deepin-wine-plugin deepin-wine-plugin-virtual deepin-wine-uninstaller:i386 deepin-wine32:i386 deepin-wine32-preloader:i386 deepin-wine32-tools:i386 deepin.com.qq.office:i386 deepin.com.wechat:i386
```

最后执行

` sudo apt autoremove`

**Comment by ArkiZh** [comment]
最近不用wine啦，关掉了哈！感谢答疑。
