### ISSUE TITLE
今天安装的TIM，登陆显示版本过低

### ISSUE THREAD

**Issue by longfeimua** [wszqkzqk/deepin-wine-ubuntu#319]
我看了下官方库TIM的时间都是18年了，但是上个月用着没任何问题

**Comment by 0xppppy** [comment]
弄了半天,不知道这样会不会有问题

先去tim官网下载最新TIM
env WINEPREFIX=~/.deepinwine/Deepin-TIM/ deepin-wine TIM安装包.exe

参考
https://blog.csdn.net/weixin_44236868/article/details/105542859

**Comment by LeoJhonSong** [comment]
楼上兄弟正解

**Comment by longfeimua** [comment]
实测能用，非常感谢

**Comment by Alcantara6** [comment]
安装后只能手机扫码登录。普通登录在加载验证码页的时候会一直加载不出来。
