### ISSUE TITLE
微信输入框显示小框框怎么解决，网上搜索的办法都不灵

### ISSUE THREAD

**Issue by johnxiongs** [wszqkzqk/deepin-wine-ubuntu#338]
![image](https://user-images.githubusercontent.com/37213061/118229199-2d327700-b4be-11eb-8884-fe431d51d15d.png)

**Comment by lyh458** [comment]
log out 然后重新log in

**Comment by yiyayamaya** [comment]
每次登录微信后的第一次在聊天窗口中打字是中文的话就没问题，如果第一次不小心输入的英文，那就重启微信然后再第一次输入中文

**Comment by lyh458** [comment]
> 每次登录微信后的第一次在聊天窗口中打字是中文的话就没问题，如果第一次不小心输入的英文，那就重启微信然后再第一次输入中文

尝试[更新到新版本](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/339)试试

**Comment by yiyayamaya** [comment]
> > 每次登录微信后的第一次在聊天窗口中打字是中文的话就没问题，如果第一次不小心输入的英文，那就重启微信然后再第一次输入中文
> 
> 尝试[更新到新版本](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/339)试试

我的新版本截图会崩溃。。。所以一直用老版本。。。

**Comment by lyh458** [comment]
> > > 每次登录微信后的第一次在聊天窗口中打字是中文的话就没问题，如果第一次不小心输入的英文，那就重启微信然后再第一次输入中文
> > 
> > 
> > 尝试[更新到新版本](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/339)试试
> 
> 我的新版本截图会崩溃。。。所以一直用老版本。。。

我试了一下：会！但我从来不用微信截图，因为功能太少了。Ubuntu我用flameshot，Windows和mac可以用snipaste，设好自己习惯的快捷键，完全可以替代微信截图。
