### ISSUE TITLE
Ubuntu18.04 gnome wechat和qq 字体太小，qq好友昵称如果有表情的话会乱码

### ISSUE THREAD

**Issue by asang24** [wszqkzqk/deepin-wine-ubuntu#45]
Ubuntu18.04 gnome wechat和qq 字体太小，找了资料不知道怎么修改..

**Comment by abcfy2** [comment]
因为wine对HiDPI不会默认适配dpi值。解决方案:

    WINEPREFIX=~/.deepinwine/你的wine容器目录  /usr/bin/deepin-wine  winecfg

注意`WINEPREFIX`这个环境变量指向你的deepin wine容器目录，比如TIM在`~/.deepinwine/Deepin-TIM`，微信在`~/.deepinwine/Deepin-WeChat`，用`tab`补全一下这个目录即可。

打开wine设置页面，在`显示`选项卡中调整`屏幕分辨率`的dpi值即可。比如想实现win 10的150% DPI只需要将`96`改到`144`即可，125%放大则对应`120`。手工调整下合适的DPI就可以了

**Comment by asang24** [comment]
Thank you !  已更改

**Comment by widon1104** [comment]
调整deepin wine qq界面的字体可以吗？

**Comment by abcfy2** [comment]
改默认字体需要改注册表的字体映射，但我记不清楚具体是哪个键值了，你可以google一下wine的字体设置

**Comment by asang24** [comment]
> 改默认字体需要改注册表的字体映射，但我记不清楚具体是哪个键值了，你可以google一下wine的字体设置

有个新问题，时不时的会出现。 会有个黑色的框在屏幕中间

**Comment by abcfy2** [comment]
Wine各种奇怪的问题我也无能为力，wine一些机制也不了解，只是简单会用而已。这个问题我暂时没在linuxmint上遇到过。目前我主要用linuxmint 19

**Comment by PinzhenChen** [comment]
@asang24 随便进一个对话框，打一个表情的中文，比如“哈哈”，黑框就变成让你选择表情的框了，然后删掉打的字，黑框就消失了。

**Comment by H-111-di** [comment]
> 因为wine对HiDPI不会默认适配dpi值。解决方案:
> 
> ```
> WINEPREFIX=~/.deepinwine/你的wine容器目录  /usr/bin/deepin-wine  winecfg
> ```
> 
> 注意`WINEPREFIX`这个环境变量指向你的deepin wine容器目录，比如TIM在`~/.deepinwine/Deepin-TIM`，微信在`~/.deepinwine/Deepin-WeChat`，用`tab`补全一下这个目录即可。
> 
> 打开wine设置页面，在`显示`选项卡中调整`屏幕分辨率`的dpi值即可。比如想实现win 10的150% DPI只需要将`96`改到`144`即可，125%放大则对应`120`。手工调整下合适的DPI就可以了

如果想要设置多个WINEPREFIX，应该怎么办呢？ 我现在设置会提示version mismatch...
