### ISSUE TITLE
Ubuntu18.04 百度云无法登陆，网络异常[1]

### ISSUE THREAD

**Issue by li-zheng-hao** [wszqkzqk/deepin-wine-ubuntu#47]

**Comment by imknown** [comment]
Temp: 多试几次就好了...

**Comment by li-zheng-hao** [comment]
> Temp: 多试几次就好了...

要是多试几次有用的话我就不会来提问了.......
emmmm 要用软件还是用Windows了，Ubuntu太折腾了

**Comment by imknown** [comment]
@li-zheng-hao 我这里多点几次登录 就登进去了. 我公司网络确实不好 经常碰这个问题.
