### ISSUE TITLE
依赖包 deepin-wine32-preloader 问题

### ISSUE THREAD

**Issue by PaPerseller** [wszqkzqk/deepin-wine-ubuntu#5]
OS: Ubuntu 18.04
安装 TIM 时出现依赖问题 "Dependency is not satisfiable: deepin-wine32-preloader"，使用dpkg强制安装仍可使用 TIM，安装微信时无此问题
TIM和微信软件包由提供的源获得

**Comment by wszqkzqk** [comment]
这个还是只能用命令安，暂时不知道是什么问题
