### ISSUE TITLE
执行install.sh 依赖库安装失败

### ISSUE THREAD

**Issue by MRYangY** [wszqkzqk/deepin-wine-ubuntu#51]
环境:Ubuntu 14
error log:
准备添加32位支持
添加成功，准备刷新apt缓存信息...
Hit http://archive.ubuntukylin.com:10006 xenial InRelease                      
Hit http://archive.ubuntukylin.com:10006 xenial/main amd64 Packages            
Hit http://archive.ubuntukylin.com:10006 xenial/main i386 Packages             
Hit http://archive.ubuntukylin.com:10006 xenial/main Translation-en            
Ign http://dl.google.com stable InRelease                                      
Ign http://cn.archive.ubuntu.com trusty InRelease                              
Hit http://security.ubuntu.com trusty-security InRelease                       
Hit http://dl.google.com stable Release.gpg                                    
Ign http://extras.ubuntu.com trusty InRelease                                  
Ign http://archive.canonical.com trusty InRelease                              
Hit http://ppa.launchpad.net artful InRelease                                  
Hit http://cn.archive.ubuntu.com trusty-updates InRelease                      
Hit http://security.ubuntu.com trusty-security/main Sources                    
Hit http://dl.google.com stable Release                                        
Hit http://extras.ubuntu.com trusty Release.gpg                                
Hit http://archive.canonical.com trusty Release.gpg                            
Hit http://cn.archive.ubuntu.com trusty-backports InRelease                    
Hit http://security.ubuntu.com trusty-security/restricted Sources              
Hit https://repo.skype.com stable InRelease                                    
Hit http://dl.google.com stable/main amd64 Packages                            
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://cn.archive.ubuntu.com trusty Release.gpg                            
Hit http://security.ubuntu.com trusty-security/universe Sources                
Hit https://repo.skype.com stable/main amd64 Packages                          
Hit http://extras.ubuntu.com trusty Release                                    
Hit http://archive.canonical.com trusty Release                                
Hit http://cn.archive.ubuntu.com trusty-updates/main Sources                   
Hit http://security.ubuntu.com trusty-security/multiverse Sources              
Hit http://extras.ubuntu.com trusty/main Sources                               
Hit http://archive.canonical.com trusty/partner amd64 Packages                 
Hit http://ppa.launchpad.net trusty InRelease                                  
Get:1 https://repo.skype.com stable/main Translation-en_US                     
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Sources             
Hit http://security.ubuntu.com trusty-security/main amd64 Packages             
Hit http://extras.ubuntu.com trusty/main amd64 Packages                        
Hit http://archive.canonical.com trusty/partner i386 Packages                  
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages       
Hit http://cn.archive.ubuntu.com trusty-updates/universe Sources               
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://extras.ubuntu.com trusty/main i386 Packages                         
Hit http://archive.canonical.com trusty/partner Translation-en                 
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages         
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Sources             
Hit http://cn.archive.ubuntu.com trusty-updates/main amd64 Packages            
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages       
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://cn.archive.ubuntu.com trusty-updates/restricted amd64 Packages      
Hit http://security.ubuntu.com trusty-security/main i386 Packages              
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages        
Hit http://cn.archive.ubuntu.com trusty-updates/universe amd64 Packages        
Ign http://ppa.launchpad.net trusty InRelease                                  
Ign http://dl.google.com stable/main Translation-en_US                         
Hit http://security.ubuntu.com trusty-security/universe i386 Packages          
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse amd64 Packages      
Ign http://dl.google.com stable/main Translation-en                            
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages        
Hit http://cn.archive.ubuntu.com trusty-updates/main i386 Packages             
Hit http://ppa.launchpad.net trusty InRelease   
Hit http://cn.archive.ubuntu.com trusty-updates/restricted i386 Packages       
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://cn.archive.ubuntu.com trusty-updates/universe i386 Packages         
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en       
Ign https://repo.skype.com stable/main Translation-en_US                       
Hit http://security.ubuntu.com trusty-security/restricted Translation-en       
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse i386 Packages       
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://security.ubuntu.com trusty-security/universe Translation-en         
Hit http://cn.archive.ubuntu.com trusty-updates/main Translation-en   
Ign https://repo.skype.com stable/main Translation-en                          
Ign http://extras.ubuntu.com trusty/main Translation-en_US                     
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Translation-en      
Hit http://ppa.launchpad.net trusty InRelease                                  
Ign http://extras.ubuntu.com trusty/main Translation-en                        
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Translation-en      
Hit http://cn.archive.ubuntu.com trusty-updates/universe Translation-en        
Hit http://ppa.launchpad.net artful/main amd64 Packages                        
Hit http://cn.archive.ubuntu.com trusty-backports/main Sources                 
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Sources           
Hit http://ppa.launchpad.net artful/main i386 Packages                         
Hit http://cn.archive.ubuntu.com trusty-backports/universe Sources             
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Sources           
Hit http://ppa.launchpad.net artful/main Translation-en                        
Hit http://cn.archive.ubuntu.com trusty-backports/main amd64 Packages          
Hit http://cn.archive.ubuntu.com trusty-backports/restricted amd64 Packages    
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://cn.archive.ubuntu.com trusty-backports/universe amd64 Packages      
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse amd64 Packages    
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://cn.archive.ubuntu.com trusty-backports/main i386 Packages           
Hit http://cn.archive.ubuntu.com trusty-backports/restricted i386 Packages     
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://cn.archive.ubuntu.com trusty-backports/universe i386 Packages       
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse i386 Packages     
Hit http://cn.archive.ubuntu.com trusty-backports/main Translation-en          
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Translation-en    
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Translation-en    
Hit http://cn.archive.ubuntu.com trusty-backports/universe Translation-en      
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://cn.archive.ubuntu.com trusty Release                                
Hit http://cn.archive.ubuntu.com trusty/main Sources                           
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://cn.archive.ubuntu.com trusty/restricted Sources                     
Hit http://cn.archive.ubuntu.com trusty/universe Sources                       
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://cn.archive.ubuntu.com trusty/multiverse Sources                     
Hit http://cn.archive.ubuntu.com trusty/main amd64 Packages                    
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://cn.archive.ubuntu.com trusty/restricted amd64 Packages              
Hit http://cn.archive.ubuntu.com trusty/universe amd64 Packages                
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://cn.archive.ubuntu.com trusty/multiverse amd64 Packages              
Hit http://cn.archive.ubuntu.com trusty/main i386 Packages                     
Hit http://cn.archive.ubuntu.com trusty/restricted i386 Packages               
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://cn.archive.ubuntu.com trusty/universe i386 Packages                 
Hit http://cn.archive.ubuntu.com trusty/multiverse i386 Packages               
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://cn.archive.ubuntu.com trusty/main Translation-en                    
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://cn.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://cn.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://cn.archive.ubuntu.com trusty/universe Translation-en                
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Ign http://cn.archive.ubuntu.com trusty/main Translation-en_US                 
Ign http://cn.archive.ubuntu.com trusty/multiverse Translation-en_US           
Hit http://ppa.launchpad.net trusty Release                                    
Ign http://cn.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://cn.archive.ubuntu.com trusty/universe Translation-en_US             
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Reading package lists... Done                                                  
即将开始安装...
(Reading database ... 226067 files and directories currently installed.)
Preparing to unpack 1.1udis86_1.72-2_i386.deb ...
Unpacking udis86 (1.72-2) over (1.72-2) ...
Preparing to unpack 1.2deepin-fonts-wine_2.18-12_all.deb ...
Unpacking deepin-fonts-wine (2.18-12) over (2.18-12) ...
Selecting previously unselected package deepin-libwine:i386.
Preparing to unpack 2.1deepin-libwine_2.18-12_i386.deb ...
Unpacking deepin-libwine:i386 (2.18-12) ...
Selecting previously unselected package deepin-libwine-dbg:i386.
Preparing to unpack 2.2deepin-libwine-dbg_2.18-12_i386.deb ...
Unpacking deepin-libwine-dbg:i386 (2.18-12) ...
Selecting previously unselected package deepin-libwine-dev:i386.
Preparing to unpack 2.3deepin-libwine-dev_2.18-12_i386.deb ...
Unpacking deepin-libwine-dev:i386 (2.18-12) ...
Selecting previously unselected package deepin-wine32.
Preparing to unpack 3.1deepin-wine32_2.18-12_i386.deb ...
Unpacking deepin-wine32 (2.18-12) ...
Selecting previously unselected package deepin-wine32-preloader.
Preparing to unpack 3.2deepin-wine32-preloader_2.18-12_i386.deb ...
Unpacking deepin-wine32-preloader (2.18-12) ...
Selecting previously unselected package deepin-wine32-tools.
Preparing to unpack 3.3deepin-wine32-tools_2.18-12_i386.deb ...
Unpacking deepin-wine32-tools (2.18-12) ...
Selecting previously unselected package deepin-wine.
Preparing to unpack 4deepin-wine_2.18-12_all.deb ...
Unpacking deepin-wine (2.18-12) ...
Selecting previously unselected package deepin-wine-binfmt.
Preparing to unpack 5deepin-wine-binfmt_2.18-12_all.deb ...
Unpacking deepin-wine-binfmt (2.18-12) ...
Preparing to unpack 6.1deepin-wine-plugin_1.0deepin2_amd64.deb ...
Unpacking deepin-wine-plugin (1.0deepin2) over (1.0deepin2) ...
Preparing to unpack 6.2deepin-wine-plugin-virtual_1.0deepin1_all.deb ...
Unpacking deepin-wine-plugin-virtual (1.0deepin1) over (1.0deepin1) ...
Preparing to unpack 7deepin-wine-helper_1.1deepin12_i386.deb ...
Unpacking deepin-wine-helper (1.1deepin12) over (1.1deepin12) ...
Preparing to unpack 8deepin-wine-uninstaller_0.1deepin2_i386.deb ...
Unpacking deepin-wine-uninstaller (0.1deepin2) over (0.1deepin2) ...
Setting up udis86 (1.72-2) ...
Setting up deepin-fonts-wine (2.18-12) ...
dpkg: dependency problems prevent configuration of deepin-libwine:i386:
 deepin-libwine:i386 depends on libc6 (>= 2.23); however:
  Version of libc6:i386 on system is 2.19-0ubuntu6.14.
 deepin-libwine:i386 depends on libstdc++6 (>= 5); however:
  Version of libstdc++6:i386 on system is 4.8.4-2ubuntu1~14.04.4.
 deepin-libwine:i386 depends on libgnutls30; however:
 deepin-libwine:i386 depends on libpng16-16; however:

dpkg: error processing package deepin-libwine:i386 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of deepin-libwine-dbg:i386:
 deepin-libwine-dbg:i386 depends on deepin-libwine (= 2.18-12); however:
  Package deepin-libwine:i386 is not configured yet.

dpkg: error processing package deepin-libwine-dbg:i386 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of deepin-libwine-dev:i386:
 deepin-libwine-dev:i386 depends on deepin-libwine (= 2.18-12); however:
  Package deepin-libwine:i386 is not configured yet.

dpkg: error processing package deepin-libwine-dev:i386 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of deepin-wine32:
 deepin-wine32 depends on deepin-libwine (= 2.18-12); however:
  Package deepin-libwine:i386 is not configured yet.

dpkg: error processing package deepin-wine32 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of deepin-wine32-preloader:
 deepin-wine32-preloader depends on deepin-wine32; however:
  Package deepin-wine32 is not configured yet.

dpkg: error processing package deepin-wine32-preloader (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of deepin-wine32-tools:
 deepin-wine32-tools depends on perl:any.
 deepin-wine32-tools depends on deepin-libwine-dev (= 2.18-12); however:
  Package deepin-libwine-dev:i386 is not configured yet.

dpkg: error processing package deepin-wine32-tools (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of deepin-wine:
 deepin-wine depends on deepin-wine64 (>= 2.18-12) | deepin-wine32 (>= 2.18-12); however:
  Package deepin-wine64 is not installed.
  Package deepin-wine32 is not configured yet.
 deepin-wine depends on deepin-wine64 (<< 2.18-12.1~) | deepin-wine32 (<< 2.18-12.1~); however:
  Package deepin-wine64 is not installed.
  Package deepin-wine32 is not configured yet.

dpkg: error processing package deepin-wine (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of deepin-wine-binfmt:
 deepin-wine-binfmt depends on deepin-wine; however:
  Package deepin-wine is not configured yet.

dpkg: error processing package deepin-wine-binfmt (--install):
 dependency problems - leaving unconfigured
Setting up deepin-wine-plugin (1.0deepin2) ...
Setting up deepin-wine-plugin-virtual (1.0deepin1) ...
Setting up deepin-wine-helper (1.1deepin12) ...
Setting up deepin-wine-uninstaller (0.1deepin2) ...
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 deepin-libwine:i386
 deepin-libwine-dbg:i386
 deepin-libwine-dev:i386
 deepin-wine32
 deepin-wine32-preloader
 deepin-wine32-tools
 deepin-wine
 deepin-wine-binfmt
安装完成，正在自动安装依赖...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  app-install-data apt-xapian-index autopoint docbook-to-man doxygen
  evolution-data-server-dev g++-4.8 gcr gir1.2-brasero-3.0 gir1.2-caribou-1.0
  gir1.2-champlain-0.12 gir1.2-clutter-1.0 gir1.2-clutter-gst-1.0
  gir1.2-cogl-1.0 gir1.2-coglpango-1.0 gir1.2-evince-3.0 gir1.2-farstream-0.2
  gir1.2-folks-0.6 gir1.2-gck-1 gir1.2-gconf-2.0 gir1.2-gcr-3
  gir1.2-gdesktopenums-3.0 gir1.2-gee-0.8 gir1.2-geocodeglib-1.0
  gir1.2-gkbd-3.0 gir1.2-gmenu-3.0 gir1.2-gnomedesktop-3.0
  gir1.2-gst-plugins-base-0.10 gir1.2-gstreamer-0.10 gir1.2-gtkchamplain-0.12
  gir1.2-gtkclutter-1.0 gir1.2-gtop-2.0 gir1.2-gucharmap-2.90
  gir1.2-gweather-3.0 gir1.2-gxps-0.1 gir1.2-json-1.0 gir1.2-mutter-3.0
  gir1.2-nautilus-3.0 gir1.2-nmgtk-1.0 gir1.2-panelapplet-4.0 gir1.2-rest-0.7
  gir1.2-rsvg-2.0 gir1.2-telepathyglib-0.12 gir1.2-xkl-1.0 gjs gnome-api-docs
  gnome-devel-docs gnome-js-common gsettings-desktop-schemas-dev
  gstreamer1.0-doc intltool itstool laptop-detect libaacs0 libarchive-dev
  libatkmm-1.6-dev libatspi2.0-dev libavcodec-ffmpeg56 libavdevice-ffmpeg56
  libavfilter-ffmpeg5 libavformat-ffmpeg56 libavresample-ffmpeg2
  libavutil-ffmpeg54 libbluray1 libbrasero-media3-dev libbs2b0 libc6-dev:i386
  libcairomm-1.0-dev libcamel1.2-dev libcanberra-doc libcaribou-common
  libcaribou-dev libcaribou0 libchamplain-0.12-0 libchamplain-0.12-dev
  libchamplain-gtk-0.12-0 libchamplain-gtk-0.12-dev libclutter-1.0-dev
  libclutter-1.0-doc libclutter-gst-1.0-0 libclutter-gst-dev
  libclutter-gtk-1.0-dev libclutter-gtk-1.0-doc libcogl-dev libcogl-doc
  libcogl-pango-dev libcroco3-dev libcrystalhd3 libdbus-1-dev
  libdbus-glib-1-dev libdconf-dev libdconf-doc libebackend1.2-dev
  libebook-contacts1.2-dev libebook1.2-dev libecal1.2-dev libedata-book1.2-dev
  libedata-cal1.2-dev libedataserver1.2-dev libegl1-mesa-dev libevince-dev
  libfarstream-0.2-dev libffi-dev libfolks-dev libgail-3-dev libgail-3-doc
  libgail-dev libgail-doc libgbm-dev libgck-1-dev libgconf2-dev libgconf2-doc
  libgcr-3-dev libgdk-pixbuf2.0-doc libgee-0.8-dev libgeocode-glib-dev
  libgeocode-glib0 libgjs0e libgles2-mesa-dev libglibmm-2.4-dev
  libglu1-mesa:i386 libgmime-2.6-dev libgnome-bluetooth-dev
  libgnome-desktop-3-dev libgnome-keyring-dev libgnome-menu-3-dev
  libgnomekbd-dev libgsm1:i386 libgstreamer-plugins-base0.10-dev
  libgstreamer-plugins-base1.0-dev libgstreamer0.10-dev libgstreamer1.0-dev
  libgtkmm-3.0-dev libgtksourceview-3.0-dev libgtksourceview-3.0-doc
  libgtop2-dev libgucharmap-2-90-dev libgweather-3-dev libgxps-dev libical-dev
  libjavascriptcoregtk-3.0-dev libjpeg62:i386 libjson-glib-dev libltdl-dev
  libmirclient-dev libmirclient7 libmirclientplatform-mesa libmirprotobuf-dev
  libmirprotobuf0 libmozjs-24-0 libmozjs-24-bin libmozjs-24-dev libmutter-dev
  libmutter0c libnautilus-extension-dev libnm-glib-dev libnm-gtk-dev
  libnm-util-dev libnotify-dev libnotify-doc libnspr4-dev libnss3-dev libntdb1
  libodbc1:i386 libopenal1:i386 libosmesa6:i386 libp11-kit-gnome-keyring
  libpanel-applet-4-0 libpanel-applet-4-dev libpanel-applet-4-doc
  libpangomm-1.4-dev libpgm-5.1-0 libpoppler-qt5-1 libpostproc-ffmpeg53
  libprotobuf-dev libprotobuf-lite8 libqtassistantclient4 librest-dev
  librsvg2-dev libsdl1.2debian libsecret-1-dev libseed-gtk3-0 libshine3
  libsigc++-2.0-dev libsoup-gnome2.4-dev libsoup2.4-dev
  libstartup-notification0-dev libstdc++-4.8-dev libswresample-ffmpeg1
  libswscale-ffmpeg3 libtasn1-3-bin libtasn1-3-dev libtasn1-bin
  libtelepathy-farstream-dev libtelepathy-glib-dev libtelepathy-glib-doc
  libtidy-0.99-0 libtotem-plparser-dev libtwolame0 libudev-dev libudisks2-dev
  libvala-0.22-0 libvte-2.90-dev libvte-2.90-doc libwacom-dev
  libwebkitgtk-3.0-dev libwebkitgtk-common-dev libwnck-3-dev libx264-142
  libx265 libxkbfile-dev libxklavier-dev libxml2-doc libxres-dev libxtst-dev
  libzmq3 libzvbi-common libzvbi0 linux-libc-dev:i386 mircommon-dev
  mutter-common network-manager-dev ocl-icd-libopencl1:i386 oneconf-common
  p11-kit-modules policykit-1-doc python-debtagshw python-dirspec
  python-gi-dev python-gobject-2-dev python-gobject-dev python-httplib2
  python-lxml python-mako python-markupsafe python-ntdb python-oneconf
  python-openssl python-pam python-piston-mini-client python-qt4 python-serial
  python-sip python-twisted-bin python-twisted-core python-twisted-web
  python-zope.interface python3-oneconf python3-piston-mini-client
  qt-faststart software-center-aptdaemon-plugins tidy ubuntu-extras-keyring
  ubuntuone-client-data valac valac-0.22 valac-0.22-vapi x11proto-record-dev
  x11proto-resource-dev xsltproc yelp-tools
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  deepin-libwine:i386 deepin-libwine-dbg:i386 deepin-libwine-dev:i386
  deepin-wine deepin-wine-binfmt deepin-wine32:i386
  deepin-wine32-preloader:i386 deepin-wine32-tools:i386
0 upgraded, 0 newly installed, 8 to remove and 177 not upgraded.
8 not fully installed or removed.
After this operation, 224 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 228962 files and directories currently installed.)
Removing deepin-wine32-preloader (2.18-12) ...
Removing deepin-wine-binfmt (2.18-12) ...
Removing deepin-wine (2.18-12) ...
Removing deepin-wine32 (2.18-12) ...
Removing deepin-wine32-tools (2.18-12) ...
Removing deepin-libwine-dev:i386 (2.18-12) ...
Removing deepin-libwine:i386 (2.18-12) ...
Removing deepin-libwine-dbg:i386 (2.18-12) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
➜  deepin-wine-ubuntu git:(master)

**Comment by Peytonlan** [comment]
deepin-libwine:i386 depends on libstdc++6 (>= 5); however:
Version of libstdc++6:i386 on system is 4.8.4-2ubuntu1~14.04.4.

系统版本太低
如果是生产用机, 没有理由在这上面装qq
如果不是生产用机, 没有理由不升级系统, Ubuntu 14.04 19年4月到期

**Comment by MRYangY** [comment]
好的 ,知道了,O(∩_∩)O谢谢

**Comment by wszqkzqk** [comment]
系统版本太低了，不支持
