### ISSUE TITLE
Lubuntu安装 http://mirrors.aliyun.com/deepin/pool/non-free/d下的软件问题

### ISSUE THREAD

**Issue by dly667** [wszqkzqk/deepin-wine-ubuntu#56]
你好。我们使用的是Lubuntu系统，安装了  http://mirrors.aliyun.com/deepin/pool/non-free/d 下的qq，tim，wechat，百度网盘，但是无法正常运行。第一次打开的时候会出现，deepin正在初始化。第二次再打开就无任何反应。求助。感谢。
以下是机器的环境。
![1](https://user-images.githubusercontent.com/26707226/50082249-71f14f80-022b-11e9-9646-63dce963563c.png)
![2](https://user-images.githubusercontent.com/26707226/50082403-d4e2e680-022b-11e9-9426-e83a0476fdd0.png)
![4](https://user-images.githubusercontent.com/26707226/50082507-22f7ea00-022c-11e9-9efb-3c4a919a40fe.png)

![3](https://user-images.githubusercontent.com/26707226/50082405-d6141380-022b-11e9-9185-0f49a54919a2.png)

**Comment by imknown** [comment]
看来还是 Xubuntu(XFCE) 最稳... 一点问题都没有... /强行安利

**Comment by Peytonlan** [comment]
如不需启用视频功能, 参照 https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12#issuecomment-443656358
如需要启用视频功能, 参照 https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12#issuecomment-444172543

**Comment by dly667** [comment]
@imknown 哈哈，我也装了Xubuntu(XFCE)。安利赞一波

**Comment by bodo005** [comment]
我是mate版,用过xfce不习惯

**Comment by wszqkzqk** [comment]
尝试运行KDE-install.sh
