### ISSUE TITLE
QQ无法发送图片，打开的文件选择对话框, 不显示任何图片

### ISSUE THREAD

**Issue by ianhitlgang** [wszqkzqk/deepin-wine-ubuntu#58]
QQ无法发送图片，打开的文件选择对话框, 不显示任何图片，
ubuntu 16.04使用的是unity ubuntu18.04也是使用unity，  
但点击发送文件的时候，对话框却正常显示文件列表， 
寻求解决方案

**Comment by imknown** [comment]
Duplicated: #6

**Comment by ianhitlgang** [comment]
其实，我是想批量导入QQ表情图和发图片，在我点开的时候才发现这个bug的。 我刚刚无意中发现， 当我在弹出的对话框中随便从外面拖一个文件进去， 那么对话框里面的图片文件全部都能正常显示出来。我估计这个bug的问题可能是对话框中的文件类型过滤有点问题， 谢谢
