### ISSUE TITLE
双屏无法显示qq wechat托盘

### ISSUE THREAD

**Issue by yd-yin** [wszqkzqk/deepin-wine-ubuntu#60]
Ubuntu16.04，一台4k屏幕，一台普通屏幕
只开启普通屏幕时可以显示托盘图标，除此以外（只开启4k屏幕 / 双屏全开）均无法显示，关闭窗口以后没法唤醒了。不知是否与HI-DPI有关。

**Comment by yd-yin** [comment]
尝试使用快捷键唤醒，但快捷键只能关闭窗口，无法唤醒窗口。
消息提示并不关键，唤醒更加重要

**Comment by omaidb** [comment]
问题+1

**Comment by omaidb** [comment]
高分屏显示太小，完全看不见啊

**Comment by sishuai** [comment]
@zq-97 
> @wszqkzqk 话说托盘图标失效的复现条件我找到了：外接双屏。单屏的时候一切正常

这个bug是在主屏的位置起始点不是(0,0)的时候才会出现【主屏在最左侧没问题】，这个时候点击不了托盘图标

原始帖见 https://bbs.deepin.org/forum.php?mod=viewthread&tid=155949

**Comment by lvtanxi** [comment]
@yd-yin 消息提示没有快捷键这个是有点恼火，不知道现在有办法解决了没有。
