### ISSUE TITLE
代码里发现 eos 挖矿？

### ISSUE THREAD

**Issue by viperlin** [wszqkzqk/deepin-wine-ubuntu#65]
我今天想看看里面的东西结果点击进去的，发现了eos, go
/home/xxx/.deepinwine/Deepin-QQ/drive_c/users/lbq/My Documents

```
drwxrwxr-x 20  4.0K 1月  17 21:20  eos
drwxrwxr-x 11  4.0K 1月  11 09:59  go

```
是不是安装包被人攻击修改了？

**Comment by imknown** [comment]
这个是 你系统 `~/Documents` 的 link 吧... 并不是 DeepinWine 的吧...

**Comment by viperlin** [comment]
@imknown 确实是这个样子，不好意思了
