### ISSUE TITLE
linux mint 18.3安装deepin-wine32-preloader后，安装容器中QQ时还是显示依赖关系deepin-wine32-preloader不满足

### ISSUE THREAD

**Issue by Face-Smile** [wszqkzqk/deepin-wine-ubuntu#7]
QQ和QQ light一样

**Comment by wszqkzqk** [comment]
暂时无解，是打包的锅，用命令安装吧

**Comment by Face-Smile** [comment]
嗯嗯，已经可以了，非常感谢

**Comment by dave-yxw** [comment]
> 暂时无解，是打包的锅，用命令安装吧

用什么命令，sudo dpkg -i不好使

`~/Downloads$ sudo dpkg -i deepin.com.wechat_2.6.2.31deepin0_i386.deb 
Selecting previously unselected package deepin.com.wechat:i386.
(Reading database ... 213845 files and directories currently installed.)
Preparing to unpack deepin.com.wechat_2.6.2.31deepin0_i386.deb ...
Unpacking deepin.com.wechat:i386 (2.6.2.31deepin0) ...
dpkg: dependency problems prevent configuration of deepin.com.wechat:i386:
 deepin.com.wechat:i386 depends on deepin-wine (>= 1.9-11).
 deepin.com.wechat:i386 depends on deepin-wine32.
 deepin.com.wechat:i386 depends on deepin-wine32-preloader.

dpkg: error processing package deepin.com.wechat:i386 (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 deepin.com.wechat:i386
`
