### ISSUE TITLE
ubuntu 18.04 dash 图标分组问题

### ISSUE THREAD

**Issue by chndzcl** [wszqkzqk/deepin-wine-ubuntu#74]
这不是一个比较大的问题，在 18.04 下面也能使用。

我安装了微信和 qq，它们共同的问题是打开的聊天窗口不使用 desktop 对应的图标，而是使用 wine 的图标。

原因是在 ubuntu 18.04 上面用 xprop WM_CLASS 点击窗口可以看到窗口的 WM_CLASS，微信的是 wecat.exe，qq 的是 qq.exe。

deb 包中定义的 desktop 文件中的 StartupWMClass 写成了 WeChat.exe，导致了这个问题。我不清楚其他发行版的是什么，为什么 StartupWMClass 要写成这样。

如果不影响其他发行版，建议可以考虑修正这个问题，我手动改了 /usr/share/applications/deepin.com.qq.im.com 的 StartupWMClass=qq.exe，/usr/share/applications/deepin.com.wechat.desktop 的 StartupWMClass=wechat.exe 就可以让窗口图标符合预期了。

**Comment by myNameIsEvanChan** [comment]
我的QQ一直显示在Win System Tray中，不能像其他软件那样显示在启动栏中，而且一旦关闭了这个框，QQ将无法再打开，进程任然在后台运行。总之我希望打开QQ以后可以不将win也显示出来，而是让他后台运行就可以了，将QQ直接显示出来就行。不知道这个问题你能不能帮我解决一下？QQ在Ubuntu基于Unity的桌面下显示是正常的。
![QQ截图20190314000518](https://user-images.githubusercontent.com/32271393/54295137-6e345580-45ed-11e9-81d4-19286ae3180a.png)

**Comment by shellexy** [comment]
嗯，咱也是这样改了 StartupWMClass=wechat.exe 来用。

另外，咱还添加了一行
`Keywords=wechat
`
以便 wine 微信能在 gnome 开始菜单敲 wechat 搜索启动
（否则的话，gnome dash 得搜索「微信」才能找到微信，然而 dash 默认不能用中文输入法）

> 这不是一个比较大的问题，在 18.04 下面也能使用。
> 
> 我安装了微信和 qq，它们共同的问题是打开的聊天窗口不使用 desktop 对应的图标，而是使用 wine 的图标。
> 
> 原因是在 ubuntu 18.04 上面用 xprop WM_CLASS 点击窗口可以看到窗口的 WM_CLASS，微信的是 wecat.exe，qq 的是 qq.exe。
> 
> deb 包中定义的 desktop 文件中的 StartupWMClass 写成了 WeChat.exe，导致了这个问题。我不清楚其他发行版的是什么，为什么 StartupWMClass 要写成这样。
> 
> 如果不影响其他发行版，建议可以考虑修正这个问题，我手动改了 /usr/share/applications/deepin.com.qq.im.com 的 StartupWMClass=qq.exe，/usr/share/applications/deepin.com.wechat.desktop 的 StartupWMClass=wechat.exe 就可以让窗口图标符合预期了。

**Comment by shellexy** [comment]
这是因为 unity 支持系统托盘，
而 ubuntu gnome shell 默认不支持系统托盘……
得自己安装并启用 gnome-shell-extension-top-icons-plus 插件才可以……
（可以在软件中心搜索安装 topicons plus）

![2019-03-14 14-18-40 的屏幕截图](https://user-images.githubusercontent.com/299902/54335512-2997d100-4664-11e9-9962-c0f9870bd2a4.png)
![2019-03-14 14-18-11 的屏幕截图](https://user-images.githubusercontent.com/299902/54335516-2ac8fe00-4664-11e9-96db-e97bce016e70.png)


> 我的QQ一直显示在Win System Tray中，不能像其他软件那样显示在启动栏中，而且一旦关闭了这个框，QQ将无法再打开，进程任然在后台运行。总之我希望打开QQ以后可以不将win也显示出来，而是让他后台运行就可以了，将QQ直接显示出来就行。不知道这个问题你能不能帮我解决一下？QQ在Ubuntu基于Unity的桌面下显示是正常的。
> ![QQ截图20190314000518](https://user-images.githubusercontent.com/32271393/54295137-6e345580-45ed-11e9-81d4-19286ae3180a.png)

**Comment by myNameIsEvanChan** [comment]
感谢，安装那个插件之后问题已经解决了

**Comment by chndzcl** [comment]
嗯，应该是deepin的包里面提供的desktop文件，不在这个项目范围内，我自己关掉吧。顺带一说，在 ubuntu 18.04 里面那个插件在单屏幕中能用，但如果电脑有双屏幕，图标闪烁后会消失。这个问题估计还要花时间看看是扩展的原因还是gnome3本身的原因。。。。

**Comment by light8lee** [comment]
> 嗯，应该是deepin的包里面提供的desktop文件，不在这个项目范围内，我自己关掉吧。顺带一说，在 ubuntu 18.04 里面那个插件在单屏幕中能用，但如果电脑有双屏幕，图标闪烁后会消失。这个问题估计还要花时间看看是扩展的原因还是gnome3本身的原因。。。。

我也是用的双屏，然后图标消失后我发现在调整topicons plus里面的属性时，图标又可以重新出现，不知道你现在是否知道问题出在哪里了

**Comment by chndzcl** [comment]
> > 嗯，应该是deepin的包里面提供的desktop文件，不在这个项目范围内，我自己关掉吧。顺带一说，在 ubuntu 18.04 里面那个插件在单屏幕中能用，但如果电脑有双屏幕，图标闪烁后会消失。这个问题估计还要花时间看看是扩展的原因还是gnome3本身的原因。。。。
> 
> 我也是用的双屏，然后TIM图标消失后我发现在调整topicons plus里面的属性时，图标又可以重新出现，不知道现在是否知道问题出在哪里了

最近还比较忙，没时间看这个；电脑现在也主要用单屏幕。估计得以后再看看。

**Comment by sishuai** [comment]
> > > 嗯，应该是deepin的包里面提供的desktop文件，不在这个项目范围内，我自己关掉吧。顺带一说，在 ubuntu 18.04 里面那个插件在单屏幕中能用，但如果电脑有双屏幕，图标闪烁后会消失。这个问题估计还要花时间看看是扩展的原因还是gnome3本身的原因。。。。
> > 
> > 
> > 我也是用的双屏，然后TIM图标消失后我发现在调整topicons plus里面的属性时，图标又可以重新出现，不知道现在是否知道问题出在哪里了
> 
> 最近还比较忙，没时间看这个；电脑现在也主要用单屏幕。估计得以后再看看。

这个bug是在主屏的位置起始点不是(0,0)的时候才会出现【主屏在最左侧没问题】，这个时候点击不了托盘图标

原始帖见 https://bbs.deepin.org/forum.php?mod=viewthread&tid=155949 第9楼

可以把左侧的设置为主屏幕，然后注销Ubuntu账号，然后重新登录

**Comment by light8lee** [comment]
> > > > 嗯，应该是deepin的包里面提供的desktop文件，不在这个项目范围内，我自己关掉吧。顺带一说，在 ubuntu 18.04 里面那个插件在单屏幕中能用，但如果电脑有双屏幕，图标闪烁后会消失。这个问题估计还要花时间看看是扩展的原因还是gnome3本身的原因。。。。
> > > 
> > > 
> > > 我也是用的双屏，然后TIM图标消失后我发现在调整topicons plus里面的属性时，图标又可以重新出现，不知道现在是否知道问题出在哪里了
> > 
> > 
> > 最近还比较忙，没时间看这个；电脑现在也主要用单屏幕。估计得以后再看看。
> 
> 这个bug是在主屏的位置起始点不是(0,0)的时候才会出现【主屏在最左侧没问题】，这个时候点击不了托盘图标
> 
> 原始帖见 https://bbs.deepin.org/forum.php?mod=viewthread&tid=155949 第9楼
> 
> 可以把左侧的设置为主屏幕，然后注销Ubuntu账号，然后重新登录

应该就是和屏幕位置有关，因为我后来把我竖着的右侧副屏横置后，调整两个屏幕对齐就再也没出现问题了
