### ISSUE TITLE
能否支持钉钉的deb包呢？

### ISSUE THREAD

**Issue by t2krew** [wszqkzqk/deepin-wine-ubuntu#75]
工作中使用钉钉，但是查看了一下包列表没有钉钉，想问下能否提供钉钉的deb包呢？

**Comment by wszqkzqk** [comment]
支持的，在我给出的deepin官方链接下下载

**Comment by wszqkzqk** [comment]
其实钉钉有原生版，不用wine https://club.doui.cc/topic/view/15c8b0ea25957196a9156b2d

**Comment by wszqkzqk** [comment]
或者这个
https://github.com/nashaofu/dingtalk

**Comment by t2krew** [comment]
@wszqkzqk  好的，感谢！

**Comment by csfreebird** [comment]
那不是原生版本，视频会议，投屏都支持不了．
