### ISSUE TITLE
那个，有办法设置一下缩放问题吗

### ISSUE THREAD

**Issue by plbin97** [wszqkzqk/deepin-wine-ubuntu#93]
那个，有办法设置一下wine的DPI吗，外面桌面设置200%，然后qq显得非常小。
想去找wine的配置，但是不知道在哪里配置。
已捐助

**Comment by plbin97** [comment]
我自己解决了
这是tim的，
执行
WINEPREFIX=~/.deepinwine/Deepin-TIM deepin-wine winecfg

**Comment by wszqkzqk** [comment]
对，就是这样设置

**Comment by omaidb** [comment]
提示： 高分辨率显示器，可在winecfg的显示选项卡中适当dpi的值，例如缩放150%，将dpi设置为144。
